import { ChoiceButtons, DualLabel, MultiCheck, NotesField } from '../../components/AssessmentControls.jsx'
import { dermatomes, nerves, neurodynamic, reflexes } from '../elbowConfig.js'

const sensoryOptions=[{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'hypoesthesia',label:'Hypoesthesia',labelAr:'نقص الحس'},{key:'paresthesia',label:'Paresthesia',labelAr:'تنميل'},{key:'numbness',label:'Numbness',labelAr:'خدر'},{key:'dysesthesia',label:'Dysesthesia',labelAr:'عسر الحس'}]
const reflexOptions=['0','1+','2+','3+','4+'].map((key)=>({key,label:key,labelAr:key}))
const neuroOptions=[{key:'negative',label:'Negative',labelAr:'سلبي'},{key:'positive',label:'Positive',labelAr:'إيجابي'},{key:'familiar_symptoms',label:'Familiar symptoms reproduced',labelAr:'إعادة إنتاج الأعراض المألوفة'},{key:'modified_by_sensitizer',label:'Modified by sensitizer',labelAr:'تغيّرت مع المحفّز'}]

function BilateralChoices({items,values,onChange,options}){return <div className="bilateral-grid">{items.map((item)=>{const current=values[item.key]||{};return <article key={item.key}><DualLabel as="h4" label={item.label} labelAr={item.labelAr}/><div><ChoiceButtons label="Right" labelAr="يمين" options={options} value={current.right||''} onChange={(next)=>onChange({...values,[item.key]:{...current,right:next}})}/><ChoiceButtons label="Left" labelAr="يسار" options={options} value={current.left||''} onChange={(next)=>onChange({...values,[item.key]:{...current,left:next}})}/></div></article>})}</div>}

export function NeurologicalSection({value,onChange}){
  function nerve(key){return value.peripheralNerves[key]||{checks:[],result:'',notes:''}}
  function updateNerve(key,field,next){onChange({...value,peripheralNerves:{...value.peripheralNerves,[key]:{...nerve(key),[field]:next}}})}
  return <div className="assessment-section__body"><section className="clinical-subsection"><DualLabel as="h3" label="Dermatomes" labelAr="القطاعات الجلدية"/><BilateralChoices items={dermatomes} values={value.sensory} options={sensoryOptions} onChange={(sensory)=>onChange({...value,sensory})}/></section><section className="clinical-subsection"><DualLabel as="h3" label="Peripheral Nerve Screen" labelAr="فحص الأعصاب الطرفية"/><div className="clinical-finding-grid">{nerves.map((item)=>{const current=nerve(item.key);return <article className="clinical-finding-card is-active" key={item.key}><DualLabel as="h4" label={item.label} labelAr={item.labelAr}/><div className="clinical-finding-controls"><MultiCheck label="Components evaluated" labelAr="العناصر المفحوصة" options={item.checks} value={current.checks} onChange={(checks)=>updateNerve(item.key,'checks',checks)}/><ChoiceButtons label="Result" labelAr="النتيجة" options={[{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'abnormal',label:'Abnormal',labelAr:'غير طبيعي'}]} value={current.result} onChange={(result)=>updateNerve(item.key,'result',result)}/><NotesField label="Nerve findings" labelAr="نتائج فحص العصب" rows={2} value={current.notes} onChange={(notes)=>updateNerve(item.key,'notes',notes)}/></div></article>})}</div></section><section className="clinical-subsection"><DualLabel as="h3" label="Reflexes" labelAr="المنعكسات"/><BilateralChoices items={reflexes} values={value.reflexes} options={reflexOptions} onChange={(reflexValues)=>onChange({...value,reflexes:reflexValues})}/><ChoiceButtons label="Comparison" labelAr="المقارنة" value={value.reflexComparison} onChange={(reflexComparison)=>onChange({...value,reflexComparison})} options={[{key:'symmetrical',label:'Symmetrical',labelAr:'متناظرة'},{key:'hyporeflexia',label:'Hyporeflexia',labelAr:'نقص المنعكسات'},{key:'absent',label:'Absent',labelAr:'غائبة'},{key:'hyperreflexia',label:'Hyperreflexia',labelAr:'فرط المنعكسات'}]}/></section><section className="clinical-subsection"><DualLabel as="h3" label="Neurodynamic Tests" labelAr="اختبارات الديناميكا العصبية"/><div className="clinical-finding-grid">{neurodynamic.map((test)=><ChoiceButtons key={test.key} label={test.label} labelAr={test.labelAr} options={neuroOptions} value={value.neurodynamic[test.key]||''} onChange={(next)=>onChange({...value,neurodynamic:{...value.neurodynamic,[test.key]:next}})}/>)}</div></section><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}
