import { BooleanChoice, ChoiceButtons, DualLabel, FindingCard, MultiCheck, NotesField, NumberField } from '../../components/AssessmentControls.jsx'
import { dynamicFindings, elbowMovements, movementQuality, palpationFindings, palpationGroups, staticFindings } from '../elbowConfig.js'

const tenderness=['0','1','2','3'].map((key)=>({key,label:key,labelAr:key}))

export function InspectionSection({value,onChange}){
  return <div className="assessment-section__body"><MultiCheck label="Static Inspection" labelAr="الفحص الثابت" options={staticFindings} value={value.staticFindings} onChange={(staticFindingsValue)=>onChange({...value,staticFindings:staticFindingsValue})}/><section className="clinical-subsection"><DualLabel as="h3" label="Dynamic Inspection" labelAr="الفحص الحركي"/><p className="clinical-guidance">Record findings separately during each movement. / سجّل النتائج بصورة منفصلة أثناء كل حركة.</p><div className="clinical-finding-grid">{elbowMovements.map((movement)=><MultiCheck key={movement.key} label={movement.label} labelAr={movement.labelAr} options={dynamicFindings} value={value.dynamic[movement.key]||[]} onChange={(findings)=>onChange({...value,dynamic:{...value.dynamic,[movement.key]:findings}})}/>)}</div></section><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function PalpationSection({value,onChange}){
  function toggle(key,active){const locations={...value.locations};if(active)locations[key]={tenderness:'',findings:[]};else delete locations[key];onChange({...value,locations})}
  function update(key,field,next){onChange({...value,locations:{...value.locations,[key]:{...value.locations[key],[field]:next}}})}
  return <div className="assessment-section__body"><p className="clinical-guidance">Select structures actually palpated, then document severity and concurrent findings. / حدّد البنى التي تم جسها ثم سجّل شدة الإيلام والنتائج المرافقة.</p>{palpationGroups.map((group)=><section className="clinical-subsection" key={group.label}><DualLabel as="h3" label={group.label} labelAr={group.labelAr}/><div className="clinical-finding-grid">{group.items.map((item)=>{const finding=value.locations[item.key];return <FindingCard item={item} key={item.key} active={Boolean(finding)} onToggle={(active)=>toggle(item.key,active)}>{finding&&<div className="clinical-finding-controls"><ChoiceButtons label="Tenderness severity" labelAr="شدة الإيلام" options={tenderness} value={String(finding.tenderness??'')} onChange={(next)=>update(item.key,'tenderness',next===''?'':Number(next))}/><MultiCheck label="Additional findings" labelAr="نتائج إضافية" options={palpationFindings} value={finding.findings} onChange={(findings)=>update(item.key,'findings',findings)}/></div>}</FindingCard>})}</div></section>)}<NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function ArticularSection({value,onChange}){
  function finding(key){return value.movements[key]||{arom:'',prom:'',pain:null,limitation:null}}
  function update(key,field,next){onChange({...value,movements:{...value.movements,[key]:{...finding(key),[field]:next}}})}
  return <div className="assessment-section__body"><section className="clinical-subsection"><DualLabel as="h3" label="AROM / PROM" labelAr="مدى الحركة الفعّال / السلبي"/><div className="rom-grid">{elbowMovements.map((movement)=>{const current=finding(movement.key);return <article className="rom-card" key={movement.key}><DualLabel as="h4" label={movement.label} labelAr={movement.labelAr}/><div className="rom-card__numbers"><NumberField label="AROM" labelAr="المدى الفعّال" min="0" max="360" suffix="°" value={current.arom} onChange={(next)=>update(movement.key,'arom',next)}/><NumberField label="PROM" labelAr="المدى السلبي" min="0" max="360" suffix="°" value={current.prom} onChange={(next)=>update(movement.key,'prom',next)}/></div><div className="rom-card__flags"><BooleanChoice label="Pain" labelAr="ألم" value={current.pain} onChange={(next)=>update(movement.key,'pain',next)}/><BooleanChoice label="Limitation" labelAr="محدودية" value={current.limitation} onChange={(next)=>update(movement.key,'limitation',next)}/></div></article>})}</div></section><ChoiceButtons label="End Feel" labelAr="الإحساس النهائي للحركة" value={value.endFeel} onChange={(endFeel)=>onChange({...value,endFeel})} options={[{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'firm',label:'Firm',labelAr:'متماسك'},{key:'hard',label:'Hard',labelAr:'صلب'},{key:'empty',label:'Empty',labelAr:'فارغ'},{key:'pain_limited',label:'Pain-limited',labelAr:'محدود بالألم'}]}/><MultiCheck label="Movement Quality" labelAr="جودة الحركة" options={movementQuality} value={value.movementQuality} onChange={(next)=>onChange({...value,movementQuality:next})}/><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}
