import { BooleanChoice, ChoiceButtons, DualLabel, MultiCheck, NotesField, NumberField } from '../../components/AssessmentControls.jsx'
import { accessoryGroups, muscleLength, muscles } from '../elbowConfig.js'

function difference(right,left){return right!==''&&right!==undefined&&left!==''&&left!==undefined?Number(Math.abs(Number(right)-Number(left)).toFixed(2)):''}
function BilateralMeasurement({title,titleAr,unit,value,onChange,min=0,max=300,classification=false}){
  function update(side,next){onChange({...value,[side]:next,difference:difference(side==='right'?next:value.right,side==='left'?next:value.left)})}
  return <article className="measurement-card"><DualLabel as="h3" label={title} labelAr={titleAr}/><div><NumberField label="Right" labelAr="يمين" min={min} max={max} suffix={unit} value={value.right??''} onChange={(next)=>update('right',next)}/><NumberField label="Left" labelAr="يسار" min={min} max={max} suffix={unit} value={value.left??''} onChange={(next)=>update('left',next)}/><NumberField label="Difference" labelAr="الفرق" suffix={unit} value={value.difference??''} readOnly onChange={()=>{}}/></div>{classification&&<ChoiceButtons label="Classification" labelAr="التصنيف" value={value.classification||''} onChange={(next)=>onChange({...value,classification:next})} options={[{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'increased_valgus',label:'Increased valgus',labelAr:'زيادة الأروح'},{key:'increased_varus',label:'Increased varus',labelAr:'زيادة الفحج'}]}/>}</article>
}

export function StrengthMobilitySection({value,onChange}){
  function mobility(key){return value.accessoryMobility[key]||{mobility:'',pain:null}}
  function updateMobility(key,field,next){onChange({...value,accessoryMobility:{...value.accessoryMobility,[key]:{...mobility(key),[field]:next}}})}
  function mmt(key){return value.mmt[key]||{right:'',left:'',pain:null}}
  function updateMmt(key,field,next){onChange({...value,mmt:{...value.mmt,[key]:{...mmt(key),[field]:next}}})}
  return <div className="assessment-section__body"><section className="clinical-subsection"><DualLabel as="h3" label="Elbow Alignment / Measurement" labelAr="محاذاة وقياسات المرفق"/><div className="measurement-grid"><BilateralMeasurement title="Carrying Angle" titleAr="زاوية الحمل" unit="°" min="-90" max="180" classification value={value.carryingAngle} onChange={(carryingAngle)=>onChange({...value,carryingAngle})}/><BilateralMeasurement title="Elbow Circumference" titleAr="محيط المرفق" unit="cm" value={value.circumference} onChange={(circumference)=>onChange({...value,circumference})}/></div></section><section className="clinical-subsection"><DualLabel as="h3" label="Accessory Mobility" labelAr="الحركة الإضافية"/>{accessoryGroups.map((group)=><div key={group.label}><DualLabel as="h4" label={group.label} labelAr={group.labelAr}/><div className="clinical-finding-grid">{group.items.map((item)=>{const current=mobility(item.key);return <article className="clinical-finding-card is-active" key={item.key}><DualLabel as="h4" label={item.label} labelAr={item.labelAr}/><div className="clinical-finding-controls"><ChoiceButtons label="Mobility" labelAr="الحركة" value={current.mobility} onChange={(next)=>updateMobility(item.key,'mobility',next)} options={[{key:'hypomobile',label:'Hypomobile',labelAr:'ناقصة'},{key:'normal',label:'Normal',labelAr:'طبيعية'},{key:'hypermobile',label:'Hypermobile',labelAr:'مفرطة'}]}/><BooleanChoice label="Pain" labelAr="ألم" value={current.pain} onChange={(next)=>updateMobility(item.key,'pain',next)}/></div></article>})}</div></div>)}</section><section className="clinical-subsection"><DualLabel as="h3" label="Manual Muscle Testing — MMT 0–5" labelAr="اختبار القوة العضلية اليدوي — 0 إلى 5"/><div className="mmt-grid">{muscles.map((item)=>{const current=mmt(item.key);return <article className="mmt-card" key={item.key}><DualLabel as="h4" label={item.label} labelAr={item.labelAr}/><div><NumberField label="Right" labelAr="يمين" min="0" max="5" suffix="/5" value={current.right} onChange={(next)=>updateMmt(item.key,'right',next)}/><NumberField label="Left" labelAr="يسار" min="0" max="5" suffix="/5" value={current.left} onChange={(next)=>updateMmt(item.key,'left',next)}/></div><BooleanChoice label="Pain" labelAr="ألم" value={current.pain} onChange={(next)=>updateMmt(item.key,'pain',next)}/></article>})}</div></section><BilateralMeasurement title="Grip Strength" titleAr="قوة القبضة" unit="kg" max="500" value={value.gripStrength} onChange={(gripStrength)=>onChange({...value,gripStrength})}/><MultiCheck label="Muscle Length" labelAr="طول العضلات" options={muscleLength} value={value.muscleLength} onChange={(next)=>onChange({...value,muscleLength:next})}/><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}
