import { useCallback,useEffect,useMemo,useRef,useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link,useNavigate,useParams } from 'react-router-dom'
import api from '../../../services/api.js'
import DashboardLayout from '../../../pages/dashboards/DashboardLayout.jsx'
import { formatUtcDate } from '../../../i18n/formatters.js'
import { DualLabel,MultiCheck,SectionIntro } from '../components/AssessmentControls.jsx'
import { lumbarSteps,pathways } from './lumbarConfig.js'
import { hasLumbarRedFlags,hasUrgentLumbarFindings,mergeLumbarAssessmentData } from './lumbarData.js'
import { ArticularSection,InspectionSection,PalpationSection } from './sections/PhysicalSections.jsx'
import { MuscularSection,NeurologicalSection,NeurodynamicSection } from './sections/NeuroMuscularSections.jsx'
import { ClinicalReasoningSection,FunctionalCapacitySection,FunctionalSection,OutcomeSection,RedFlagsSection,SpecialTestsSection } from './sections/FinalSections.jsx'
import '../clinicalAssessments.css'
const components={inspection:InspectionSection,palpation:PalpationSection,articular:ArticularSection,muscular:MuscularSection,neurological:NeurologicalSection,neurodynamic:NeurodynamicSection,specialTests:SpecialTestsSection,functional:FunctionalSection,functionalCapacity:FunctionalCapacitySection,redFlags:RedFlagsSection,outcomeMeasure:OutcomeSection,clinicalReasoning:ClinicalReasoningSection}
const base=new Set(['inspection','palpation','articular','muscular','specialTests','functional','functionalCapacity','redFlags','outcomeMeasure','clinicalReasoning'])
function patientName(p){return[p?.first_name,p?.last_name].filter(Boolean).join(' ')}
function visible(data){if(!data||data.specialTests.showFull)return lumbarSteps;const p=new Set(data.specialTests.pathways);return lumbarSteps.filter((s)=>base.has(s.key)||(s.key==='neurological'&&['red_flags','neurological','leg_symptoms'].some((k)=>p.has(k)))||(s.key==='neurodynamic'&&['neurological','leg_symptoms'].some((k)=>p.has(k))))}
export default function LumbarAssessment(){
 const{patientId,assessmentId}=useParams();const{t,i18n}=useTranslation('clinical');const navigate=useNavigate();const topRef=useRef(null);const version=useRef(0);const saving=useRef(false)
 const[context,setContext]=useState(null);const[data,setData]=useState(null);const[side,setSide]=useState('');const[appointmentId,setAppointmentId]=useState('');const[activeKey,setActiveKey]=useState('inspection');const[loading,setLoading]=useState(true);const[dirty,setDirty]=useState(false);const[saveState,setSaveState]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('')
 useEffect(()=>{let active=true;setLoading(true);setError('');api.get(`/physiotherapist/patients/${patientId}/assessments/${assessmentId}`).then((response)=>{if(!active)return;const loaded=response.data.data;if(loaded.assessment.body_region!=='lumbar')throw new Error('Incorrect assessment type');setContext(loaded);setData(mergeLumbarAssessmentData(loaded.assessment.assessment_data));setSide(loaded.assessment.affected_side||'');setAppointmentId(loaded.assessment.appointment_id||'')}).catch(()=>active&&setError(t('assessment.loadError'))).finally(()=>active&&setLoading(false));return()=>{active=false}},[assessmentId,patientId,t])
 const readOnly=context?.assessment?.status==='completed';const steps=useMemo(()=>visible(data),[data]);const index=Math.max(0,steps.findIndex((s)=>s.key===activeKey));const current=steps[index]||steps[0];const Section=components[current?.key];const percent=Math.round(((index+1)/steps.length)*100)
 useEffect(()=>{if(data&&!steps.some((s)=>s.key===activeKey))setActiveKey('inspection')},[activeKey,data,steps])
 const save=useCallback(async(status='draft',{automatic=false}={})=>{if(!context||!data||readOnly||saving.current)return false;const captured=version.current;saving.current=true;setSaveState('saving');setError('');setNotice('');try{const response=await api.patch(`/physiotherapist/patients/${patientId}/assessments/${assessmentId}`,{status,affected_side:side||null,appointment_id:appointmentId||null,assessment_data:data});setContext((c)=>({...c,assessment:response.data.data}));if(captured===version.current)setDirty(false);setSaveState('saved');if(status==='completed')setNotice(t('assessment.completed'));return true}catch{setSaveState('');setError(t(status==='completed'?'assessment.completeError':'assessment.saveError'));return false}finally{saving.current=false;if(automatic)setTimeout(()=>setSaveState((s)=>s==='saved'?'':s),1800)}},[appointmentId,assessmentId,context,data,patientId,readOnly,side,t])
 useEffect(()=>{if(!dirty||readOnly||!data)return undefined;const timer=setTimeout(()=>void save('draft',{automatic:true}),1400);return()=>clearTimeout(timer)},[appointmentId,data,dirty,readOnly,save,side])
 function changed(callback){callback();version.current+=1;setDirty(true);setSaveState('');setNotice('')}function updateSection(next){changed(()=>setData((d)=>({...d,[current.key]:next})))}function updatePaths(next){changed(()=>setData((d)=>({...d,specialTests:{...d.specialTests,pathways:next}})))}function toggleFull(){changed(()=>setData((d)=>({...d,specialTests:{...d.specialTests,showFull:!d.specialTests.showFull}})))}function go(i){setActiveKey(steps[i].key);requestAnimationFrame(()=>topRef.current?.scrollIntoView({behavior:'smooth',block:'start'}))}
 const appointments=useMemo(()=>(context?.appointments||[]).map((a)=>({...a,label:`${formatUtcDate(a.starts_at,i18n.resolvedLanguage,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})} · ${a.treatment_type}`})),[context?.appointments,i18n.resolvedLanguage]);const anyFlags=hasLumbarRedFlags(data);const urgent=hasUrgentLumbarFindings(data)
 return <DashboardLayout role={t('assessment.role')} title={t('lumbar.title')} subtitle={t('lumbar.subtitle')}><main className="clinical-assessment-shell lumbar-assessment" ref={topRef}><Link className="text-button" to={`/physiotherapist/patients/${patientId}`}>← {t('assessment.back')}</Link>{loading&&<div className="panel clinical-profile-loading" role="status"><span/><span/><span/></div>}{!loading&&error&&!context&&<section className="panel clinical-error" role="alert"><p>{error}</p><button className="button" type="button" onClick={()=>navigate(0)}>{t('profile.retry')}</button></section>}{context&&data&&<>
 <header className="panel assessment-workspace-header"><div><p className="eyebrow">{context.assessment.parent_assessment_id?'Lumbar Reassessment / إعادة تقييم العمود القطني':'Lumbar Spine Assessment / تقييم العمود الفقري القطني'}</p><h2>{patientName(context.patient)}</h2><p>{t('assessment.step',{current:index+1,total:steps.length})} · {current.label}</p></div><span className={`assessment-save-state assessment-save-state--${readOnly?'locked':saveState||'idle'}`}>{readOnly?t('assessment.readOnly'):saveState==='saving'?t('assessment.saving'):saveState==='saved'?t('assessment.saved'):dirty?t('assessment.unsaved'):t('assessment.saved')}</span></header>
 {anyFlags&&<div className={`clinical-safety-alert ${urgent?'clinical-safety-alert--urgent':''}`} role="alert"><strong>{urgent?'URGENT CLINICAL WARNING — urgent medical assessment / referral may be required.':'Clinical Safety Alert — red-flag findings have been recorded.'}</strong><span dir="rtl" lang="ar">{urgent?'تحذير سريري عاجل — قد يلزم تقييم أو إحالة طبية عاجلة.':'تنبيه سلامة سريري — تم تسجيل علامات حمراء.'}</span><p>This alert does not create an automatic diagnosis.</p></div>}
 <fieldset className="clinical-assessment-fieldset" disabled={readOnly}><section className="panel neck-pathway-panel"><div><DualLabel as="h2" label="Lumbar Clinical Decision Pathway" labelAr="مسار القرار السريري القطني"/><p>Select relevant presentation patterns. Targeted sections will appear automatically.</p></div><MultiCheck label="Presentation / Findings" labelAr="العرض / النتائج" options={pathways} value={data.specialTests.pathways} onChange={updatePaths}/><button className={`button ${data.specialTests.showFull?'':'button--quiet'}`} type="button" aria-pressed={data.specialTests.showFull} onClick={toggleFull}>{data.specialTests.showFull?'Use Targeted View / استخدام العرض الموجّه':'View Full Assessment / عرض التقييم الكامل'}</button></section></fieldset>
 <section className="panel assessment-progress" aria-label={t('assessment.completion')}><div className="assessment-progress__mobile"><strong>{String(index+1).padStart(2,'0')} / {String(steps.length).padStart(2,'0')}</strong><DualLabel label={current.label} labelAr={current.labelAr}/></div><nav>{steps.map((s,i)=><button type="button" key={s.key} className={i===index?'is-current':i<index?'is-passed':''} onClick={()=>go(i)}><span>{String(lumbarSteps.findIndex((x)=>x.key===s.key)+1).padStart(2,'0')}</span><small>{s.label}</small></button>)}</nav><div className="assessment-progress__bar" role="progressbar" aria-valuenow={percent} aria-valuemin="0" aria-valuemax="100"><span style={{width:`${percent}%`}}/></div></section>
 {context.previous_assessment&&<div className="clinical-previous-banner"><span>{t('assessment.previousAssessment')}</span><Link to={`/physiotherapist/patients/${patientId}/assessments/lumbar/${context.previous_assessment.id}`}>{t('profile.view')}</Link></div>}
 <fieldset className="clinical-assessment-fieldset" disabled={readOnly}><section className="panel assessment-metadata"><fieldset><legend>{t('assessment.affectedSide')}</legend><div className="assessment-side-options">{['right','left','bilateral'].map((o)=><label className={side===o?'is-selected':''} key={o}><input type="radio" checked={side===o} onChange={()=>changed(()=>setSide(o))}/><span>{t(`lumbar.${o}`)}</span></label>)}</div></fieldset><label><span>{t('assessment.linkedSession')}</span><select value={appointmentId} onChange={(e)=>changed(()=>setAppointmentId(e.target.value))}><option value="">{t('assessment.noSession')}</option>{appointments.map((a)=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label></section><section className="panel assessment-section"><SectionIntro number={lumbarSteps.findIndex((s)=>s.key===current.key)+1} title={current.label} titleAr={current.labelAr}/><Section value={data[current.key]} onChange={updateSection} assessmentData={data}/></section></fieldset>
 {error&&<div className="clinical-save-message clinical-save-message--error" role="alert">{error}</div>}{notice&&<div className="clinical-save-message" role="status">{notice}</div>}<footer className="panel assessment-actions"><button className="button button--quiet" type="button" disabled={index===0} onClick={()=>go(index-1)}>← {t('assessment.previous')}</button>{!readOnly&&<button className="button button--quiet" type="button" disabled={saveState==='saving'} onClick={()=>void save('draft')}>{t('assessment.saveDraft')}</button>}{index<steps.length-1?<button className="button" type="button" onClick={()=>go(index+1)}>{t('assessment.next')} →</button>:!readOnly&&<button className="button" type="button" disabled={saveState==='saving'} onClick={()=>void save('completed')}>{t('assessment.complete')}</button>}</footer>
 </>}</main></DashboardLayout>
}
