import { ChoiceButtons, DualLabel, NotesField, NumberField, TextList } from '../../components/AssessmentControls.jsx'
import { activities, functionalTasks, motorTests, specialGroups } from '../neckConfig.js'
import { hasNeurologicalConcern } from '../neckData.js'

const difficulty=[{key:'none',label:'None',labelAr:'لا يوجد'},{key:'mild',label:'Mild',labelAr:'خفيف'},{key:'moderate',label:'Moderate',labelAr:'متوسط'},{key:'severe',label:'Severe',labelAr:'شديد'},{key:'unable',label:'Unable',labelAr:'غير قادر'}]
const taskOptions=[{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'limited',label:'Limited',labelAr:'محدود'},{key:'painful',label:'Painful',labelAr:'مؤلم'},{key:'unable',label:'Unable',labelAr:'غير قادر'}]
const fullResultOptions=[{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'abnormal',label:'Abnormal',labelAr:'غير طبيعي'},{key:'positive',label:'Positive',labelAr:'إيجابي'},{key:'negative',label:'Negative',labelAr:'سلبي'},{key:'unable',label:'Unable',labelAr:'غير قادر'},{key:'not_tested',label:'Not Tested',labelAr:'لم يُختبر'}]
const specialResultOptions=[{key:'positive',label:'Positive',labelAr:'إيجابي'},{key:'negative',label:'Negative',labelAr:'سلبي'},{key:'not_tested',label:'Not Tested',labelAr:'لم يُختبر'}]

export function FunctionalSection({value,onChange}){
  return <div className="assessment-section__body"><section className="clinical-subsection"><DualLabel as="h3" label="Daily Activities" labelAr="الأنشطة اليومية"/><div className="clinical-finding-grid">{activities.map((activity)=><ChoiceButtons key={activity.key} label={activity.label} labelAr={activity.labelAr} options={difficulty} value={value.activities[activity.key]||''} onChange={(next)=>onChange({...value,activities:{...value.activities,[activity.key]:next}})}/>)}</div></section><section className="clinical-subsection"><DualLabel as="h3" label="Functional Cervical Tasks" labelAr="المهام الوظيفية للرقبة"/><div className="clinical-finding-grid">{functionalTasks.map((task)=><ChoiceButtons key={task.key} label={task.label} labelAr={task.labelAr} options={taskOptions} value={value.tasks[task.key]||''} onChange={(next)=>onChange({...value,tasks:{...value.tasks,[task.key]:next}})}/>)}</div></section><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function MotorControlSection({value,onChange}){
  return <div className="assessment-section__body"><p className="clinical-guidance">Select the result that best describes performance. Use Not Tested when the test was not clinically indicated. / اختر النتيجة الأنسب واستخدم «لم يُختبر» عندما لا يكون الاختبار مطلوباً سريرياً.</p><div className="special-test-grid">{motorTests.map((test)=><ChoiceButtons key={test.key} label={test.label} labelAr={test.labelAr} options={fullResultOptions} value={value.tests[test.key]||''} onChange={(next)=>onChange({...value,tests:{...value.tests,[test.key]:next}})}/>)}</div><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function SpecialTestsSection({value,onChange,assessmentData}){
  const activeGroups=value.showFull?Object.keys(specialGroups):value.pathways.filter((key)=>specialGroups[key])
  const clusterKeys=['spurling','ultt1','cervical_distraction','rotation_under_60']
  const positiveCluster=clusterKeys.filter((key)=>value.tests[key]==='positive').length
  function optionsFor(key){return ['gait_balance','hand_dexterity','upper_cervical_mobility','upper_cervical_palpation','cervical_movement_reproduction'].includes(key)?fullResultOptions:specialResultOptions}
  return <div className="assessment-section__body">{positiveCluster>=3&&<div className="clinical-hypothesis-alert" role="status"><strong>Cervical radiculopathy hypothesis strengthened</strong><span dir="rtl" lang="ar">تعززت فرضية الاعتلال الجذري العنقي</span><p>This cluster supports a clinical hypothesis; it does not create a definitive diagnosis.</p></div>}{hasNeurologicalConcern(assessmentData)&&<div className="clinical-safety-alert" role="alert"><strong>Neurological warning — consider the referral pathway</strong><span dir="rtl" lang="ar">تحذير عصبي — يجب النظر في مسار الإحالة</span><p>Interpret the complete pattern and follow clinical protocol. Do not diagnose from one positive test.</p></div>}<p className="clinical-guidance clinical-guidance--important">Only pathways selected in the clinical decision panel are shown. “View Full Assessment” remains available as a manual override. / تظهر المسارات المحددة فقط، ويمكن عرض التقييم الكامل عند الحاجة السريرية.</p>{activeGroups.map((key)=>{const group=specialGroups[key];return <section className="clinical-subsection special-test-pathway" key={key}><DualLabel as="h3" label={group.label} labelAr={group.labelAr}/>{key==='thoracic_outlet'&&<p className="clinical-guidance">No individual thoracic-outlet test confirms a diagnosis automatically. Interpret neurological, vascular, and history findings together. / لا يؤكد أي اختبار منفرد التشخيص آلياً.</p>}<div className="special-test-grid">{group.tests.map((test)=><ChoiceButtons key={test.key} label={test.label} labelAr={test.labelAr} options={optionsFor(test.key)} value={value.tests[test.key]||''} onChange={(next)=>onChange({...value,tests:{...value.tests,[test.key]:next}})}/>)}</div></section>})}{!activeGroups.length&&<div className="clinical-empty-inline">Select a relevant clinical pathway above or choose View Full Assessment. / حدّد مساراً سريرياً مناسباً أو اختر عرض التقييم الكامل.</div>}<NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function OutcomeSection({value,onChange}){
  return <div className="assessment-section__body"><section className="clinical-subsection"><DualLabel as="h3" label="Neck Disability Index — NDI" labelAr="مؤشر عجز الرقبة — NDI"/><NumberField label="Score" labelAr="الدرجة" min="0" max="50" suffix="/50" value={value.ndi} onChange={(ndi)=>onChange({...value,ndi})}/></section><section className="clinical-subsection"><DualLabel as="h3" label="Patient-Specific Functional Scale — PSFS" labelAr="مقياس الوظيفة الخاص بالمريض — PSFS"/><div className="psfs-grid">{value.psfs.map((entry,index)=><article key={index}><label className="clinical-text-field"><DualLabel label={`Activity ${index+1}`} labelAr={`النشاط ${index+1}`}/><input value={entry.activity} onChange={(event)=>{const psfs=value.psfs.map((item,itemIndex)=>itemIndex===index?{...item,activity:event.target.value}:item);onChange({...value,psfs})}}/></label><NumberField label="Score" labelAr="الدرجة" min="0" max="10" suffix="/10" value={entry.score} onChange={(score)=>{const psfs=value.psfs.map((item,itemIndex)=>itemIndex===index?{...item,score}:item);onChange({...value,psfs})}}/></article>)}</div></section><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function ClinicalReasoningSection({value,onChange}){
  return <div className="assessment-section__body"><div className="clinical-guidance clinical-guidance--important"><strong>Clinical reasoning and referral decisions remain the physiotherapist's responsibility.</strong><span dir="rtl" lang="ar">يبقى الاستدلال السريري وقرار الإحالة من مسؤولية أخصائي العلاج الطبيعي.</span></div><NotesField label="Main Hypothesis" labelAr="الفرضية الأساسية" value={value.mainHypothesis} onChange={(mainHypothesis)=>onChange({...value,mainHypothesis})}/><TextList label="Differential Diagnosis" labelAr="التشخيص التفريقي" values={value.differentialDiagnosis} onChange={(differentialDiagnosis)=>onChange({...value,differentialDiagnosis})}/><TextList label="Findings Supporting Hypothesis" labelAr="النتائج الداعمة للفرضية" values={value.supportingFindings} onChange={(supportingFindings)=>onChange({...value,supportingFindings})}/><TextList label="Findings Against" labelAr="النتائج غير الداعمة" values={value.againstFindings} onChange={(againstFindings)=>onChange({...value,againstFindings})}/><TextList label="Tests Needed" labelAr="الاختبارات المطلوبة" values={value.testsNeeded} onChange={(testsNeeded)=>onChange({...value,testsNeeded})}/><NotesField label="Clinical Interpretation" labelAr="التفسير السريري" rows={6} value={value.interpretation} onChange={(interpretation)=>onChange({...value,interpretation})}/></div>
}
