import { BooleanChoice, ChoiceButtons, DualLabel, MultiCheck, NotesField, NumberField } from '../../components/AssessmentControls.jsx'
import { dermatomes, myelopathySymptoms, myotomes, radicularTests, reflexes, vascularSymptoms } from '../neckConfig.js'
import { hasNeurologicalConcern, hasVascularConcern } from '../neckData.js'

const sensoryOptions=[{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'hypoesthesia',label:'Hypoesthesia',labelAr:'نقص الحس'},{key:'paresthesia',label:'Paresthesia',labelAr:'تنميل'},{key:'numbness',label:'Numbness',labelAr:'خدر'},{key:'dysesthesia',label:'Dysesthesia',labelAr:'عسر الحس'}]
const reflexOptions=['0','1+','2+','3+','4+'].map((key)=>({key,label:key,labelAr:key}))
const resultOptions=[{key:'positive',label:'Positive',labelAr:'إيجابي'},{key:'negative',label:'Negative',labelAr:'سلبي'},{key:'not_tested',label:'Not Tested',labelAr:'لم يُختبر'}]
const normalOptions=[{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'abnormal',label:'Abnormal',labelAr:'غير طبيعي'},{key:'not_tested',label:'Not Tested',labelAr:'لم يُختبر'}]

function SafetyAlert({type='neurological',children}){return <div className={`clinical-safety-alert clinical-safety-alert--${type}`} role="alert"><strong>{type==='vascular'?'Potential neurological / vascular concern':'Abnormal neurological findings detected'}</strong><span dir="rtl" lang="ar">{type==='vascular'?'اشتباه عصبي / وعائي محتمل':'تم تسجيل نتائج عصبية غير طبيعية'}</span><p>{children}</p></div>}

function BilateralChoices({items,values,onChange,options}){return <div className="bilateral-grid">{items.map((item)=>{const current=values[item.key]||{};return <article key={item.key}><DualLabel as="h4" label={item.label} labelAr={item.labelAr}/><div><ChoiceButtons label="Right" labelAr="يمين" options={options} value={current.right||''} onChange={(next)=>onChange({...values,[item.key]:{...current,right:next}})}/><ChoiceButtons label="Left" labelAr="يسار" options={options} value={current.left||''} onChange={(next)=>onChange({...values,[item.key]:{...current,left:next}})}/></div></article>})}</div>}

export function NeurologicalSection({value,onChange,assessmentData}){
  function myotome(key){return value.myotomes[key]||{right:'',left:''}}
  function updateMyotome(key,side,next){onChange({...value,myotomes:{...value.myotomes,[key]:{...myotome(key),[side]:next}}})}
  return <div className="assessment-section__body">{hasNeurologicalConcern(assessmentData)&&<SafetyAlert>Consider medical referral according to clinical protocol. This warning does not establish a diagnosis.</SafetyAlert>}<section className="clinical-subsection"><DualLabel as="h3" label="Sensory / Dermatomes C2–T1" labelAr="الحس / القطاعات الجلدية C2–T1"/><BilateralChoices items={dermatomes} values={value.sensory} options={sensoryOptions} onChange={(sensory)=>onChange({...value,sensory})}/></section><section className="clinical-subsection"><DualLabel as="h3" label="Myotomes — MMT /5" labelAr="القطاعات العضلية — القوة /5"/><div className="mmt-grid">{myotomes.map((item)=>{const current=myotome(item.key);return <article className="mmt-card" key={item.key}><DualLabel as="h4" label={item.label} labelAr={item.labelAr}/><div><NumberField label="Right" labelAr="يمين" min="0" max="5" suffix="/5" value={current.right} onChange={(next)=>updateMyotome(item.key,'right',next)}/><NumberField label="Left" labelAr="يسار" min="0" max="5" suffix="/5" value={current.left} onChange={(next)=>updateMyotome(item.key,'left',next)}/></div></article>})}</div></section><section className="clinical-subsection"><DualLabel as="h3" label="Reflexes" labelAr="المنعكسات"/><BilateralChoices items={reflexes} values={value.reflexes} options={reflexOptions} onChange={(reflexValues)=>onChange({...value,reflexes:reflexValues})}/><ChoiceButtons label="Comparison" labelAr="المقارنة" value={value.reflexComparison} onChange={(reflexComparison)=>onChange({...value,reflexComparison})} options={[{key:'symmetrical',label:'Symmetrical',labelAr:'متناظرة'},{key:'hyporeflexia',label:'Hyporeflexia',labelAr:'نقص المنعكسات'},{key:'absent',label:'Absent',labelAr:'غائبة'},{key:'hyperreflexia',label:'Hyperreflexia',labelAr:'فرط المنعكسات'}]}/></section><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function RadicularSection({value,onChange,assessmentData}){
  function finding(key){return value.tests[key]||{result:'',familiarSymptoms:null,sensitizerChange:null,sideDifference:''}}
  function update(key,field,next){onChange({...value,tests:{...value.tests,[key]:{...finding(key),[field]:next}}})}
  return <div className="assessment-section__body">{hasNeurologicalConcern(assessmentData)&&<SafetyAlert>Review the neurological pattern and consider the appropriate referral or cervical radiculopathy pathway.</SafetyAlert>}<p className="clinical-guidance">Document test findings as evidence supporting or opposing a hypothesis. No result confirms a diagnosis automatically. / وثّق النتائج كأدلة داعمة أو غير داعمة للفرضية دون تشخيص آلي.</p><div className="special-test-grid">{radicularTests.map((test)=>{const current=finding(test.key);return <article key={test.key}><DualLabel as="h4" label={test.label} labelAr={test.labelAr}/><ChoiceButtons label="Result" labelAr="النتيجة" value={current.result} options={resultOptions} onChange={(next)=>update(test.key,'result',next)}/><BooleanChoice label="Familiar symptoms reproduced" labelAr="إعادة إنتاج الأعراض المألوفة" value={current.familiarSymptoms} onChange={(next)=>update(test.key,'familiarSymptoms',next)}/><BooleanChoice label="Changed by sensitizing manoeuvre" labelAr="تغيرت مع مناورة التحسيس" value={current.sensitizerChange} onChange={(next)=>update(test.key,'sensitizerChange',next)}/><label className="clinical-text-field"><DualLabel label="Side-to-side difference" labelAr="الفرق بين الجانبين"/><input value={current.sideDifference} onChange={(event)=>update(test.key,'sideDifference',event.target.value)}/></label></article>})}</div><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function UmnSection({value,onChange,assessmentData}){
  const tests=[{key:'hoffmann',label:'Hoffmann',labelAr:'هوفمان',options:resultOptions},{key:'babinski',label:'Babinski',labelAr:'بابنسكي',options:resultOptions},{key:'clonus',label:'Clonus',labelAr:'الرمع',options:resultOptions},{key:'gait',label:'Gait assessment',labelAr:'تقييم المشي',options:normalOptions},{key:'balance',label:'Balance',labelAr:'التوازن',options:normalOptions},{key:'hand_dexterity',label:'Hand dexterity',labelAr:'مهارة اليد',options:normalOptions}]
  return <div className="assessment-section__body">{hasNeurologicalConcern(assessmentData)&&<SafetyAlert>Neurological warning — a medical referral pathway should be considered according to clinical protocol. One finding alone is not a diagnosis of myelopathy.</SafetyAlert>}<div className="special-test-grid">{tests.map((test)=><ChoiceButtons key={test.key} label={test.label} labelAr={test.labelAr} options={test.options} value={value.tests[test.key]||''} onChange={(next)=>onChange({...value,tests:{...value.tests,[test.key]:next}})}/>)}</div><MultiCheck label="Myelopathy Symptoms" labelAr="أعراض محتملة مرتبطة بالنخاع" options={myelopathySymptoms} value={value.myelopathySymptoms} onChange={(next)=>onChange({...value,myelopathySymptoms:next})}/><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function VascularSection({value,onChange,assessmentData}){
  return <div className="assessment-section__body">{hasVascularConcern(assessmentData)&&<SafetyAlert type="vascular">Do not treat this as a routine musculoskeletal presentation. Clinical review or referral may be required according to protocol.</SafetyAlert>}<BooleanChoice label="Vascular screen clinically indicated" labelAr="الفحص الوعائي مطلوب سريرياً" value={value.indicated} onChange={(indicated)=>onChange({...value,indicated})}/><MultiCheck label="Vertebrobasilar / Vascular Symptoms" labelAr="أعراض الدوران الفقري القاعدي / الأوعية" options={vascularSymptoms} value={value.symptoms} onChange={(symptoms)=>onChange({...value,symptoms})}/><div className="clinical-guidance clinical-guidance--important">These findings are safety prompts only and must not be used as an automatic vascular diagnosis. / هذه النتائج مؤشرات سلامة فقط ولا تُستخدم كتشخيص وعائي آلي.</div><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}
