import { BooleanChoice, ChoiceButtons, DualLabel, FindingCard, MultiCheck, NotesField, NumberField } from '../../components/AssessmentControls.jsx'
import { cervicalSegments, dynamicFindings, movementQuality, movements, palpationFindings, palpationGroups, staticFindings } from '../neckConfig.js'

const tenderness=['0','1','2','3'].map((key)=>({key,label:key,labelAr:key}))
const mobilityOptions=[{key:'hypomobile',label:'Hypomobile',labelAr:'ناقص الحركة'},{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'hypermobile',label:'Hypermobile',labelAr:'مفرط الحركة'}]

export function InspectionSection({value,onChange}){
  return <div className="assessment-section__body"><MultiCheck label="Static Inspection" labelAr="الفحص الثابت" options={staticFindings} value={value.staticFindings} onChange={(staticFindingsValue)=>onChange({...value,staticFindings:staticFindingsValue})}/><MultiCheck label="Dynamic Inspection During Cervical Movement" labelAr="الفحص الحركي أثناء حركة الرقبة" options={dynamicFindings} value={value.dynamicFindings} onChange={(dynamicFindingsValue)=>onChange({...value,dynamicFindings:dynamicFindingsValue})}/><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function PalpationSection({value,onChange}){
  function toggle(key,active){const locations={...value.locations};if(active)locations[key]={tenderness:'',findings:[]};else delete locations[key];onChange({...value,locations})}
  function update(key,field,next){onChange({...value,locations:{...value.locations,[key]:{...value.locations[key],[field]:next}}})}
  return <div className="assessment-section__body"><p className="clinical-guidance">Select only structures examined, then document tenderness and concurrent findings. / حدّد البنى المفحوصة فقط ثم وثّق الإيلام والنتائج المرافقة.</p>{palpationGroups.map((group)=><section className="clinical-subsection" key={group.label}><DualLabel as="h3" label={group.label} labelAr={group.labelAr}/><div className="clinical-finding-grid">{group.items.map((item)=>{const finding=value.locations[item.key];return <FindingCard item={item} key={item.key} active={Boolean(finding)} onToggle={(active)=>toggle(item.key,active)}>{finding&&<div className="clinical-finding-controls"><ChoiceButtons label="Tenderness 0–3" labelAr="شدة الإيلام 0–3" options={tenderness} value={String(finding.tenderness??'')} onChange={(next)=>update(item.key,'tenderness',next===''?'':Number(next))}/><MultiCheck label="Additional Findings" labelAr="نتائج إضافية" options={palpationFindings} value={finding.findings} onChange={(findings)=>update(item.key,'findings',findings)}/></div>}</FindingCard>})}</div></section>)}<NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function ArticularSection({value,onChange}){
  function finding(key){return value.movements[key]||{arom:'',prom:'',pain:null,limitation:null}}
  function update(key,field,next){onChange({...value,movements:{...value.movements,[key]:{...finding(key),[field]:next}}})}
  return <div className="assessment-section__body"><section className="clinical-subsection"><DualLabel as="h3" label="Cervical AROM / PROM" labelAr="مدى الحركة العنقية الفعّال / السلبي"/><div className="rom-grid">{movements.map((movement)=>{const current=finding(movement.key);return <article className="rom-card" key={movement.key}><DualLabel as="h4" label={movement.label} labelAr={movement.labelAr}/><div className="rom-card__numbers"><NumberField label="AROM" labelAr="المدى الفعّال" min="0" max="180" suffix="°" value={current.arom} onChange={(next)=>update(movement.key,'arom',next)}/><NumberField label="PROM" labelAr="المدى السلبي" min="0" max="180" suffix="°" value={current.prom} onChange={(next)=>update(movement.key,'prom',next)}/></div><div className="rom-card__flags"><BooleanChoice label="Pain" labelAr="ألم" value={current.pain} onChange={(next)=>update(movement.key,'pain',next)}/><BooleanChoice label="Limitation" labelAr="محدودية" value={current.limitation} onChange={(next)=>update(movement.key,'limitation',next)}/></div></article>})}</div></section><MultiCheck label="Movement Quality" labelAr="جودة الحركة" options={movementQuality} value={value.movementQuality} onChange={(next)=>onChange({...value,movementQuality:next})}/><ChoiceButtons label="End Feel" labelAr="الإحساس النهائي للحركة" value={value.endFeel} onChange={(endFeel)=>onChange({...value,endFeel})} options={[{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'firm',label:'Firm',labelAr:'متماسك'},{key:'hard',label:'Hard',labelAr:'صلب'},{key:'empty',label:'Empty',labelAr:'فارغ'},{key:'pain_limited',label:'Pain-limited',labelAr:'محدود بالألم'}]}/><section className="clinical-subsection"><DualLabel as="h3" label="Segmental Mobility" labelAr="الحركة القطعية"/><div className="segmental-mobility-grid">{cervicalSegments.map((segment)=><ChoiceButtons key={segment.key} label={segment.label} labelAr={segment.labelAr} options={mobilityOptions} value={value.segmentalMobility[segment.key]||''} onChange={(next)=>onChange({...value,segmentalMobility:{...value.segmentalMobility,[segment.key]:next}})}/>)}</div></section><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}
