import { apiError } from '../utils/http.js';

const SECTIONS = ['inspection','palpation','articular','strengthMobility','neurological','specialTests','functional','outcomeMeasure','clinicalReasoning'];
const STATIC = new Set(['posture','carrying_angle','valgus','varus','deformity','swelling','ecchymosis','redness','scar','muscle_atrophy','asymmetry','protective_position']);
const DYNAMIC_MOVEMENTS = new Set(['flexion','extension','pronation','supination']);
const DYNAMIC_FINDINGS = new Set(['limited_rom','painful_movement','compensation','instability','crepitus','locking','catching']);
const PALPATION = new Set(['medial_epicondyle','lateral_epicondyle','olecranon','radial_head','capitulum','trochlea','coronoid_process','ulnar_shaft','radial_shaft','humeroulnar_joint','humeroradial_joint','proximal_radioulnar_joint','common_extensor_tendon','common_flexor_tendon','biceps_tendon','triceps_tendon','brachialis','pronator_teres','supinator','anconeus']);
const PALPATION_FINDINGS = new Set(['local_tenderness','swelling','increased_temperature','muscle_spasm','trigger_point','tendon_tenderness']);
const MOVEMENTS = new Set(['flexion','extension','pronation','supination']);
const ACCESSORY = new Set(['humeroulnar_medial','humeroulnar_lateral','humeroulnar_anterior','humeroulnar_posterior','humeroradial_anterior','humeroradial_posterior','radial_head_anterior','radial_head_posterior']);
const MUSCLES = new Set(['biceps','brachialis','brachioradialis','triceps','wrist_extensors','wrist_flexors','pronators','supinators','grip']);
const MUSCLE_LENGTH = new Set(['wrist_flexor_tightness','wrist_extensor_tightness','pronator_tightness','supinator_tightness','biceps_tightness','triceps_tightness']);
const DERMATOMES = new Set(['c5','c6','c7','c8','t1']);
const NERVES = new Set(['radial','median','ulnar']);
const REFLEXES = new Set(['biceps_c5_6','brachioradialis_c6','triceps_c7']);
const NEURODYNAMIC = new Set(['ultt1','ultt2a','ultt2b','ultt3']);
const PATHWAYS = new Set(['lateral','medial','anterior','posterior','instability','posterolateral_instability','ulnar_nerve','radioulnar','neurological']);
const SPECIAL_TESTS = new Set(['resisted_wrist_extension','cozens','mills','maudsleys','resisted_wrist_flexion','resisted_pronation_medial','golfers_elbow','resisted_supination_biceps','resisted_elbow_flexion','hook_test','resisted_elbow_extension','triceps_palpation','valgus_stress','varus_stress','moving_valgus','lateral_pivot_shift','chair_push_up_instability','tinels_cubital','elbow_flexion_test','ulnar_neurodynamic','radial_head_mobility','proximal_radioulnar_assessment','resisted_supination_radioulnar','resisted_pronation_radioulnar']);
const ACTIVITIES = new Set(['eating','drinking','dressing','washing_hair','brushing_teeth','carrying_objects','opening_door','opening_jar','writing','computer_mouse']);
const SPORTS = new Set(['tennis','golf','boxing','weightlifting','climbing','throwing','racquet_sports','manual_work']);
const FUNCTIONAL_TESTS = new Set(['push_up','chair_push_up','closed_chain_loading']);

function asObject(value,path){if(!value||typeof value!=='object'||Array.isArray(value))throw apiError(`${path} must be an object`,400);return value}
function keys(value,allowed,path){const unknown=Object.keys(value).filter((key)=>!allowed.has(key));if(unknown.length)throw apiError(`${path} contains unsupported fields`,400)}
function numeric(value,path,min,max){if(value===''||value===null||value===undefined)return;const number=Number(value);if(!Number.isFinite(number)||number<min||number>max)throw apiError(`${path} must be between ${min} and ${max}`,400)}
function string(value,path,max=2000){if(value===''||value===null||value===undefined)return;if(typeof value!=='string'||value.length>max)throw apiError(`${path} must be valid text`,400)}
function bool(value,path){if(value!==null&&value!==undefined&&typeof value!=='boolean')throw apiError(`${path} must be true, false, or empty`,400)}
function choice(value,allowed,path){if(value===''||value===null||value===undefined)return;if(!allowed.has(value))throw apiError(`${path} is invalid`,400)}
function selections(value,allowed,path,max=30){if(value===undefined)return;if(!Array.isArray(value)||value.length>max||value.some((item)=>typeof item!=='string'||!allowed.has(item)))throw apiError(`${path} contains invalid selections`,400)}
function textList(value,path){if(value===undefined)return;if(!Array.isArray(value)||value.length>20)throw apiError(`${path} must be a list`,400);value.forEach((item,index)=>string(item,`${path}.${index}`,500))}

function inspection(section){section=asObject(section,'inspection');keys(section,new Set(['staticFindings','dynamic','notes']),'inspection');selections(section.staticFindings,STATIC,'inspection.staticFindings');const dynamic=asObject(section.dynamic||{},'inspection.dynamic');keys(dynamic,DYNAMIC_MOVEMENTS,'inspection.dynamic');for(const [movement,findings] of Object.entries(dynamic))selections(findings,DYNAMIC_FINDINGS,`inspection.dynamic.${movement}`);string(section.notes,'inspection.notes')}
function palpation(section){section=asObject(section,'palpation');keys(section,new Set(['locations','notes']),'palpation');const locations=asObject(section.locations||{},'palpation.locations');keys(locations,PALPATION,'palpation.locations');for(const [location,finding] of Object.entries(locations)){asObject(finding,location);keys(finding,new Set(['tenderness','findings']),location);numeric(finding.tenderness,`${location}.tenderness`,0,3);selections(finding.findings,PALPATION_FINDINGS,`${location}.findings`)}string(section.notes,'palpation.notes')}
function articular(section){section=asObject(section,'articular');keys(section,new Set(['movements','endFeel','movementQuality','notes']),'articular');const movements=asObject(section.movements||{},'articular.movements');keys(movements,MOVEMENTS,'articular.movements');for(const [movement,finding] of Object.entries(movements)){asObject(finding,movement);keys(finding,new Set(['arom','prom','pain','limitation']),movement);numeric(finding.arom,`${movement}.arom`,0,360);numeric(finding.prom,`${movement}.prom`,0,360);bool(finding.pain,`${movement}.pain`);bool(finding.limitation,`${movement}.limitation`)}choice(section.endFeel,new Set(['normal','firm','hard','empty','pain_limited']),'articular.endFeel');selections(section.movementQuality,new Set(['normal','stiffness','pain','catching','crepitus','locking']),'articular.movementQuality');string(section.notes,'articular.notes')}
function bilateralMeasurement(value,path,min,max){value=asObject(value||{},path);keys(value,new Set(['right','left','difference','classification']),path);numeric(value.right,`${path}.right`,min,max);numeric(value.left,`${path}.left`,min,max);numeric(value.difference,`${path}.difference`,-max,max)}
function strengthMobility(section){section=asObject(section,'strengthMobility');keys(section,new Set(['carryingAngle','circumference','accessoryMobility','mmt','gripStrength','muscleLength','notes']),'strengthMobility');bilateralMeasurement(section.carryingAngle,'carryingAngle',-90,180);choice(section.carryingAngle?.classification,new Set(['normal','increased_valgus','increased_varus']),'carryingAngle.classification');bilateralMeasurement(section.circumference,'circumference',0,300);const accessory=asObject(section.accessoryMobility||{},'accessoryMobility');keys(accessory,ACCESSORY,'accessoryMobility');for(const [key,finding] of Object.entries(accessory)){asObject(finding,key);keys(finding,new Set(['mobility','pain']),key);choice(finding.mobility,new Set(['hypomobile','normal','hypermobile']),`${key}.mobility`);bool(finding.pain,`${key}.pain`)}const mmt=asObject(section.mmt||{},'mmt');keys(mmt,MUSCLES,'mmt');for(const [key,finding] of Object.entries(mmt)){asObject(finding,key);keys(finding,new Set(['right','left','pain']),key);numeric(finding.right,`${key}.right`,0,5);numeric(finding.left,`${key}.left`,0,5);bool(finding.pain,`${key}.pain`)}bilateralMeasurement(section.gripStrength,'gripStrength',0,500);selections(section.muscleLength,MUSCLE_LENGTH,'muscleLength');string(section.notes,'strengthMobility.notes')}
function neurological(section){section=asObject(section,'neurological');keys(section,new Set(['sensory','peripheralNerves','reflexes','reflexComparison','neurodynamic','notes']),'neurological');const sensory=asObject(section.sensory||{},'sensory');keys(sensory,DERMATOMES,'sensory');for(const [key,finding] of Object.entries(sensory)){asObject(finding,key);keys(finding,new Set(['right','left']),key);for(const side of ['right','left'])choice(finding[side],new Set(['normal','hypoesthesia','paresthesia','numbness','dysesthesia']),`${key}.${side}`)}const nerves=asObject(section.peripheralNerves||{},'peripheralNerves');keys(nerves,NERVES,'peripheralNerves');for(const [key,finding] of Object.entries(nerves)){asObject(finding,key);keys(finding,new Set(['checks','result','notes']),key);if(finding.checks!==undefined&&(!Array.isArray(finding.checks)||finding.checks.some((item)=>typeof item!=='string')))throw apiError(`${key}.checks is invalid`,400);choice(finding.result,new Set(['normal','abnormal']),`${key}.result`);string(finding.notes,`${key}.notes`,1000)}const reflexes=asObject(section.reflexes||{},'reflexes');keys(reflexes,REFLEXES,'reflexes');for(const [key,finding] of Object.entries(reflexes)){asObject(finding,key);keys(finding,new Set(['right','left']),key);for(const side of ['right','left'])choice(finding[side],new Set(['0','1+','2+','3+','4+']),`${key}.${side}`)}choice(section.reflexComparison,new Set(['symmetrical','hyporeflexia','absent','hyperreflexia']),'reflexComparison');const neurodynamic=asObject(section.neurodynamic||{},'neurodynamic');keys(neurodynamic,NEURODYNAMIC,'neurodynamic');for(const [key,value] of Object.entries(neurodynamic))choice(value,new Set(['negative','positive','familiar_symptoms','modified_by_sensitizer']),key);string(section.notes,'neurological.notes')}
function specialTests(section){section=asObject(section,'specialTests');keys(section,new Set(['pathways','tests','ulnarSymptoms','notes']),'specialTests');selections(section.pathways,PATHWAYS,'specialTests.pathways');const tests=asObject(section.tests||{},'specialTests.tests');keys(tests,SPECIAL_TESTS,'specialTests.tests');for(const [key,value] of Object.entries(tests))choice(value,new Set(['positive','negative','pain','no_pain','normal','abnormal']),key);selections(section.ulnarSymptoms,new Set(['paresthesia','numbness','pain']),'specialTests.ulnarSymptoms');string(section.notes,'specialTests.notes')}
function functional(section){
  section=asObject(section,'functional');
  keys(section,new Set(['activities','loading','sports','specificMovement','sportPain','gripStrength','tests','notes']),'functional');
  const activities=asObject(section.activities||{},'functional.activities');keys(activities,ACTIVITIES,'functional.activities');
  for(const [key,value] of Object.entries(activities))choice(value,new Set(['none','mild','moderate','severe','unable']),key);
  const loading=asObject(section.loading||{},'functional.loading');keys(loading,new Set(['push','pull','carry','grip']),'functional.loading');
  for(const key of ['push','pull']){const group=asObject(loading[key]||{},key);keys(group,new Set(['activities','pain']),key);if(group.activities!==undefined&&(!Array.isArray(group.activities)||group.activities.some((item)=>typeof item!=='string')))throw apiError(`${key}.activities is invalid`,400);numeric(group.pain,`${key}.pain`,0,10)}
  const carry=asObject(loading.carry||{},'carry');keys(carry,new Set(['weight','distance','pain']),'carry');numeric(carry.weight,'carry.weight',0,1000);numeric(carry.distance,'carry.distance',0,100000);numeric(carry.pain,'carry.pain',0,10);
  choice(loading.grip,new Set(['normal','weak','painful']),'loading.grip');selections(section.sports,SPORTS,'functional.sports');string(section.specificMovement,'specificMovement',500);numeric(section.sportPain,'sportPain',0,10);
  bilateralMeasurement(section.gripStrength,'functional.gripStrength',0,500);
  const tests=asObject(section.tests||{},'functional.tests');keys(tests,FUNCTIONAL_TESTS,'functional.tests');for(const [key,value] of Object.entries(tests))choice(value,new Set(['normal','pain','weakness','unable','instability']),key);string(section.notes,'functional.notes');
}
function outcome(section){section=asObject(section,'outcomeMeasure');keys(section,new Set(['prtee','quickdash','psfs','notes']),'outcomeMeasure');numeric(section.prtee,'outcomeMeasure.prtee',0,100);numeric(section.quickdash,'outcomeMeasure.quickdash',0,100);if(section.psfs!==undefined){if(!Array.isArray(section.psfs)||section.psfs.length>3)throw apiError('PSFS must contain up to three activities',400);section.psfs.forEach((entry,index)=>{asObject(entry,`psfs.${index}`);keys(entry,new Set(['activity','score']),`psfs.${index}`);string(entry.activity,`psfs.${index}.activity`,500);numeric(entry.score,`psfs.${index}.score`,0,10)})}string(section.notes,'outcomeMeasure.notes')}
function reasoning(section){section=asObject(section,'clinicalReasoning');keys(section,new Set(['primaryHypothesis','differentialDiagnosis','supportingFindings','againstFindings','confirmationTests','interpretation']),'clinicalReasoning');string(section.primaryHypothesis,'primaryHypothesis',3000);string(section.interpretation,'interpretation',5000);for(const key of ['differentialDiagnosis','supportingFindings','againstFindings','confirmationTests'])textList(section[key],key)}

export function validateElbowAssessmentData(value,{completed=false}={}){
  const data=asObject(value,'assessment_data');if(JSON.stringify(data).length>250000)throw apiError('Assessment data is too large',413);keys(data,new Set(SECTIONS),'assessment_data');if(completed){const missing=SECTIONS.filter((key)=>!data[key]);if(missing.length)throw apiError('All assessment sections must be present before completion',400)}
  const validators=[inspection,palpation,articular,strengthMobility,neurological,specialTests,functional,outcome,reasoning];SECTIONS.forEach((key,index)=>{if(data[key]!==undefined)validators[index](data[key])});return data
}
