import { apiError } from '../utils/http.js';

const SECTIONS=['inspection','palpation','articular','muscular','neurological','neurodynamic','specialTests','functional','functionalCapacity','redFlags','outcomeMeasure','clinicalReasoning'];
const STATIC=new Set(['posture','lumbar_lordosis','scoliosis_asymmetry','pelvic_tilt','pelvic_rotation','trunk_shift','muscle_atrophy','swelling','bruising','scar','antalgic_posture']);
const DYNAMIC_MOVEMENTS=new Set(['flexion','extension','rotation','side_bending']);
const DYNAMIC_FINDINGS=new Set(['limited_movement','painful_movement','compensation','aberrant_movement','gower_sign','instability_catch','lateral_shift','poor_lumbopelvic_control']);
const PALPATION=new Set(['l1_l5_spinous','transverse_processes','facet_joints','sacrum','psis','si_joint','iliac_crest','greater_trochanter','erector_spinae','multifidus','quadratus_lumborum','gluteus_maximus','gluteus_medius','piriformis','hamstrings','iliopsoas']);
const PALPATION_FINDINGS=new Set(['muscle_spasm','increased_tone','trigger_point','local_tenderness','joint_tenderness']);
const MOVEMENTS=new Set(['flexion','extension','rotation_right','rotation_left','side_flexion_right','side_flexion_left']);
const MOVEMENT_RESPONSE=new Set(['pain_during','pain_end_range','pain_returning_flexion','referred_pain','peripheralization','centralization','no_change']);
const REPEATED=new Set(['repeated_flexion','repeated_extension','repeated_side_glide']);
const SEGMENTS=new Set(['l1_l2','l2_l3','l3_l4','l4_l5','l5_s1']);
const MUSCLES=new Set(['hip_flexors','hip_extensors','hip_abductors','hip_adductors','knee_extensors','knee_flexors','ankle_dorsiflexors','great_toe_extensors','plantar_flexors']);
const TRUNK=new Set(['abdominal_control','trunk_flexor_endurance','back_extensor_endurance','gluteal_strength','lumbopelvic_control']);
const LENGTH=new Set(['hamstrings_tight','hip_flexors_tight','rectus_femoris_tight','piriformis_tight','quadratus_lumborum_tight']);
const DERMATOMES=new Set(['l1','l2','l3','l4','l5','s1']);
const MYOTOMES=new Set(['l2_hip_flexion','l3_knee_extension','l4_ankle_dorsiflexion','l5_great_toe_extension','s1_plantarflexion']);
const REFLEXES=new Set(['patellar_l3_4','achilles_s1']);
const NEURO_TESTS=new Set(['slr','slump','femoral_nerve','crossed_slr']);
const SLR_FINDINGS=new Set(['familiar_symptoms','neural_symptoms','hamstring_stretch_only','modified_by_sensitizer']);
const PATHWAYS=new Set(['red_flags','neurological','local_pain','mechanical','leg_symptoms','stenosis','si_joint','instability','hip_differential']);
const SPECIAL_TESTS=new Set(['slr','crossed_slr','slump','neurological_exam','walking_tolerance','standing_tolerance','relief_sitting_flexion','extension_provocation','two_stage_treadmill','si_distraction','thigh_thrust','si_compression','sacral_thrust','gaenslen','prone_instability','aberrant_movement','passive_lumbar_extension','faber','fadir','hip_rom','scour']);
const ACTIVITIES=new Set(['sitting','standing','walking','stairs','getting_out_chair','bed_mobility','dressing','bending','lifting','carrying']);
const MOVEMENT_TESTS=new Set(['sit_to_stand','squat','forward_bend']);
const WALK_SYMPTOMS=new Set(['none','local_lumbar_pain','leg_pain','numbness','weakness']);
const RED_FLAGS=new Set(['major_trauma','suspected_fracture','history_cancer','unexplained_weight_loss','fever_infection','severe_unremitting_pain','bowel_bladder_dysfunction','saddle_anesthesia','progressive_neurological_deficit','bilateral_neurological_symptoms']);

function obj(v,p){if(!v||typeof v!=='object'||Array.isArray(v))throw apiError(`${p} must be an object`,400);return v}
function keys(v,a,p){const bad=Object.keys(v).filter((k)=>!a.has(k));if(bad.length)throw apiError(`${p} contains unsupported fields`,400)}
function num(v,p,min,max){if(v===''||v===null||v===undefined)return;const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw apiError(`${p} must be between ${min} and ${max}`,400)}
function str(v,p,max=2000){if(v===''||v===null||v===undefined)return;if(typeof v!=='string'||v.length>max)throw apiError(`${p} must be valid text`,400)}
function bool(v,p){if(v!==null&&v!==undefined&&typeof v!=='boolean')throw apiError(`${p} must be true, false, or empty`,400)}
function choice(v,a,p){if(v===''||v===null||v===undefined)return;if(!a.has(v))throw apiError(`${p} is invalid`,400)}
function picks(v,a,p,max=30){if(v===undefined)return;if(!Array.isArray(v)||v.length>max||v.some((x)=>typeof x!=='string'||!a.has(x)))throw apiError(`${p} contains invalid selections`,400)}
function texts(v,p){if(v===undefined)return;if(!Array.isArray(v)||v.length>20)throw apiError(`${p} must be a list`,400);v.forEach((x,i)=>str(x,`${p}.${i}`,500))}
function bilateral(v,p,min=0,max=5,withPain=false){v=obj(v||{},p);keys(v,new Set(withPain?['right','left','pain']:['right','left']),p);num(v.right,`${p}.right`,min,max);num(v.left,`${p}.left`,min,max);if(withPain)bool(v.pain,`${p}.pain`)}

function inspection(s){s=obj(s,'inspection');keys(s,new Set(['staticFindings','dynamic','notes']),'inspection');picks(s.staticFindings,STATIC,'inspection.staticFindings');const d=obj(s.dynamic||{},'inspection.dynamic');keys(d,DYNAMIC_MOVEMENTS,'inspection.dynamic');for(const[k,v]of Object.entries(d))picks(v,DYNAMIC_FINDINGS,k);str(s.notes,'inspection.notes')}
function palpation(s){s=obj(s,'palpation');keys(s,new Set(['locations','notes']),'palpation');const l=obj(s.locations||{},'palpation.locations');keys(l,PALPATION,'palpation.locations');for(const[k,v]of Object.entries(l)){obj(v,k);keys(v,new Set(['tenderness','findings']),k);num(v.tenderness,`${k}.tenderness`,0,3);picks(v.findings,PALPATION_FINDINGS,`${k}.findings`)}str(s.notes,'palpation.notes')}
function articular(s){s=obj(s,'articular');keys(s,new Set(['movements','movementResponse','repeatedMovements','segmentalMobility','notes']),'articular');const m=obj(s.movements||{},'articular.movements');keys(m,MOVEMENTS,'articular.movements');for(const[k,v]of Object.entries(m)){obj(v,k);keys(v,new Set(['rom','pain','limitation']),k);num(v.rom,`${k}.rom`,0,180);bool(v.pain,`${k}.pain`);bool(v.limitation,`${k}.limitation`)}picks(s.movementResponse,MOVEMENT_RESPONSE,'articular.movementResponse');const r=obj(s.repeatedMovements||{},'articular.repeatedMovements');keys(r,REPEATED,'articular.repeatedMovements');for(const[k,v]of Object.entries(r))choice(v,new Set(['better','worse','no_change','centralization','peripheralization']),k);const sg=obj(s.segmentalMobility||{},'articular.segmentalMobility');keys(sg,SEGMENTS,'articular.segmentalMobility');for(const[k,v]of Object.entries(sg))choice(v,new Set(['hypomobile','normal','hypermobile']),k);str(s.notes,'articular.notes')}
function muscular(s){s=obj(s,'muscular');keys(s,new Set(['mmt','trunkAssessment','muscleLength','notes']),'muscular');const m=obj(s.mmt||{},'muscular.mmt');keys(m,MUSCLES,'muscular.mmt');for(const[k,v]of Object.entries(m))bilateral(v,k,0,5,true);const t=obj(s.trunkAssessment||{},'muscular.trunkAssessment');keys(t,TRUNK,'muscular.trunkAssessment');for(const[k,v]of Object.entries(t))choice(v,new Set(['normal','reduced','poor','unable']),k);picks(s.muscleLength,LENGTH,'muscular.muscleLength');str(s.notes,'muscular.notes')}
function neurological(s){s=obj(s,'neurological');keys(s,new Set(['sensory','myotomes','reflexes','reflexComparison','notes']),'neurological');const sen=obj(s.sensory||{},'sensory');keys(sen,DERMATOMES,'sensory');for(const[k,v]of Object.entries(sen)){obj(v,k);keys(v,new Set(['right','left']),k);for(const side of['right','left'])choice(v[side],new Set(['normal','hypoesthesia','paresthesia','numbness','dysesthesia']),`${k}.${side}`)}const myo=obj(s.myotomes||{},'myotomes');keys(myo,MYOTOMES,'myotomes');for(const[k,v]of Object.entries(myo))bilateral(v,k);const ref=obj(s.reflexes||{},'reflexes');keys(ref,REFLEXES,'reflexes');for(const[k,v]of Object.entries(ref)){obj(v,k);keys(v,new Set(['right','left']),k);for(const side of['right','left'])choice(v[side],new Set(['0','1+','2+','3+','4+']),`${k}.${side}`)}choice(s.reflexComparison,new Set(['symmetrical','hyporeflexia','absent','hyperreflexia']),'reflexComparison');str(s.notes,'neurological.notes')}
function neurodynamic(s){s=obj(s,'neurodynamic');keys(s,new Set(['tests','slrAngle','slrFindings','sideDifference','notes']),'neurodynamic');const t=obj(s.tests||{},'neurodynamic.tests');keys(t,NEURO_TESTS,'neurodynamic.tests');for(const[k,v]of Object.entries(t))choice(v,new Set(['positive','negative','not_tested']),k);num(s.slrAngle,'slrAngle',0,180);picks(s.slrFindings,SLR_FINDINGS,'slrFindings');str(s.sideDifference,'sideDifference',500);str(s.notes,'neurodynamic.notes')}
function special(s){s=obj(s,'specialTests');keys(s,new Set(['pathways','showFull','tests','notes']),'specialTests');picks(s.pathways,PATHWAYS,'specialTests.pathways');bool(s.showFull,'specialTests.showFull');const t=obj(s.tests||{},'specialTests.tests');keys(t,SPECIAL_TESTS,'specialTests.tests');for(const[k,v]of Object.entries(t))choice(v,new Set(['positive','negative','normal','abnormal','better','worse','no_change','not_tested']),k);str(s.notes,'specialTests.notes')}
function functional(s){s=obj(s,'functional');keys(s,new Set(['activities','movementTests','singleLegStance','notes']),'functional');const a=obj(s.activities||{},'functional.activities');keys(a,ACTIVITIES,'functional.activities');for(const[k,v]of Object.entries(a))choice(v,new Set(['none','mild','moderate','severe','unable']),k);const m=obj(s.movementTests||{},'functional.movementTests');keys(m,MOVEMENT_TESTS,'functional.movementTests');for(const[k,v]of Object.entries(m))choice(v,new Set(['normal','pain','compensation','weakness','limited','poor_lumbopelvic_control','gower_sign']),k);bilateral(s.singleLegStance,'functional.singleLegStance',0,3600);str(s.notes,'functional.notes')}
function capacity(s){s=obj(s,'functionalCapacity');keys(s,new Set(['walkingDistance','walkingTime','walkingSymptoms','sittingTolerance','standingTolerance','liftingMaximum','notes']),'functionalCapacity');num(s.walkingDistance,'walkingDistance',0,1000000);num(s.walkingTime,'walkingTime',0,100000);picks(s.walkingSymptoms,WALK_SYMPTOMS,'walkingSymptoms');num(s.sittingTolerance,'sittingTolerance',0,100000);num(s.standingTolerance,'standingTolerance',0,100000);num(s.liftingMaximum,'liftingMaximum',0,10000);str(s.notes,'functionalCapacity.notes')}
function redFlags(s){s=obj(s,'redFlags');keys(s,new Set(['findings','notes']),'redFlags');picks(s.findings,RED_FLAGS,'redFlags.findings');str(s.notes,'redFlags.notes')}
function outcome(s){s=obj(s,'outcomeMeasure');keys(s,new Set(['odi','rolandMorris','psfs','notes']),'outcomeMeasure');num(s.odi,'odi',0,50);num(s.rolandMorris,'rolandMorris',0,24);if(s.psfs!==undefined){if(!Array.isArray(s.psfs)||s.psfs.length>3)throw apiError('PSFS must contain up to three activities',400);s.psfs.forEach((v,i)=>{obj(v,`psfs.${i}`);keys(v,new Set(['activity','score']),`psfs.${i}`);str(v.activity,`psfs.${i}.activity`,500);num(v.score,`psfs.${i}.score`,0,10)})}str(s.notes,'outcomeMeasure.notes')}
function reasoning(s){s=obj(s,'clinicalReasoning');keys(s,new Set(['primaryHypothesis','differentialDiagnosis','supportingFindings','againstFindings','testsRequired','physiotherapyDiagnosis','treatmentReferral','interpretation']),'clinicalReasoning');for(const k of['primaryHypothesis','physiotherapyDiagnosis','treatmentReferral'])str(s[k],k,3000);str(s.interpretation,'interpretation',5000);for(const k of['differentialDiagnosis','supportingFindings','againstFindings','testsRequired'])texts(s[k],k)}

export function validateLumbarAssessmentData(value,{completed=false}={}){const d=obj(value,'assessment_data');if(JSON.stringify(d).length>300000)throw apiError('Assessment data is too large',413);keys(d,new Set(SECTIONS),'assessment_data');if(completed){const missing=SECTIONS.filter((k)=>!d[k]);if(missing.length)throw apiError('All assessment sections must be present before completion',400)}const validators=[inspection,palpation,articular,muscular,neurological,neurodynamic,special,functional,capacity,redFlags,outcome,reasoning];SECTIONS.forEach((k,i)=>{if(d[k]!==undefined)validators[i](d[k])});return d}
