import { apiError } from '../utils/http.js';

const SECTIONS = ['inspection','palpation','articular','muscular','neurological','radicular','umnScreen','vascularScreen','functional','motorControl','specialTests','outcomeMeasure','clinicalReasoning'];
const STATIC_FINDINGS = new Set(['posture','forward_head','cervical_lordosis','head_tilt_rotation','shoulder_asymmetry','scapular_position','muscle_atrophy','swelling','redness','bruising','scar','protective_posture']);
const DYNAMIC_FINDINGS = new Set(['limited_movement','compensation','painful_movement','tremor','muscle_guarding','abnormal_movement']);
const PALPATION_STRUCTURES = new Set(['occiput','c1','c2','c3_c7','spinous_processes','transverse_processes','facet_joints','clavicle','first_rib','upper_trapezius','levator_scapulae','scm','scalenes','suboccipitals','splenius','semispinalis','cervical_extensors']);
const PALPATION_FINDINGS = new Set(['muscle_spasm','increased_tone','trigger_point','joint_tenderness','temperature_change']);
const MOVEMENTS = new Set(['flexion','extension','rotation_right','rotation_left','lateral_flexion_right','lateral_flexion_left']);
const MOVEMENT_QUALITY = new Set(['normal','stiffness','pain','catching','compensation']);
const SEGMENTS = new Set(['c0_c1','c1_c2','c2_c3','c3_c4','c4_c5','c5_c6','c6_c7','c7_t1']);
const MUSCLES = new Set(['cervical_flexors','cervical_extensors','lateral_flexors','rotators','upper_trapezius','scapular_retractors','serratus_anterior']);
const MUSCLE_LENGTH = new Set(['upper_trapezius_tight','levator_scapulae_tight','scm_tight','scalenes_tight','pectoralis_minor_tight','suboccipital_tightness']);
const MUSCLE_CONTROL = new Set(['normal','poor_cervical_control','excessive_upper_trapezius','scapular_dyskinesis']);
const DERMATOMES = new Set(['c2','c3','c4','c5','c6','c7','c8','t1']);
const MYOTOMES = new Set(['c4_shoulder_elevation','c5_shoulder_abduction','c6_wrist_extension','c7_elbow_extension','c8_finger_flexion','t1_finger_abduction']);
const REFLEXES = new Set(['biceps_c5_6','brachioradialis_c6','triceps_c7']);
const RADICULAR_TESTS = new Set(['spurling','cervical_distraction','ultt1_median','ultt2b_radial','ultt3_ulnar','shoulder_abduction_relief']);
const UMN_TESTS = new Set(['hoffmann','babinski','clonus','gait','balance','hand_dexterity']);
const MYELOPATHY_SYMPTOMS = new Set(['hand_clumsiness','difficulty_buttoning','gait_disturbance','balance_problems','bilateral_symptoms','progressive_weakness']);
const VASCULAR_SYMPTOMS = new Set(['dizziness','diplopia','dysarthria','dysphagia','drop_attacks','nausea','nystagmus','facial_limb_sensory_changes']);
const ACTIVITIES = new Set(['driving','computer_work','reading','sleeping','looking_up','looking_down','turning_head','dressing','lifting','carrying']);
const FUNCTIONAL_TASKS = new Set(['rotation_right','rotation_left','flexion_reading','flexion_phone','flexion_computer','extension_overhead','extension_reaching_shelf','extension_work']);
const MOTOR_TESTS = new Set(['cervical_flexion_rotation','deep_neck_flexor_endurance','craniocervical_flexion','joint_position_error','scapular_control','functional_rotation','functional_extension']);
const PATHWAYS = new Set(['red_flags','radicular','headache','local_pain','motor_control','vascular','thoracic_outlet']);
const SPECIAL_TESTS = new Set(['spurling','ultt1','cervical_distraction','rotation_under_60','hoffmann','babinski','clonus','gait_balance','hand_dexterity','cervical_flexion_rotation','upper_cervical_mobility','upper_cervical_palpation','cervical_movement_reproduction','roos_east','ultt_tos','adson']);

function asObject(value,path){if(!value||typeof value!=='object'||Array.isArray(value))throw apiError(`${path} must be an object`,400);return value}
function knownKeys(value,allowed,path){const unknown=Object.keys(value).filter((key)=>!allowed.has(key));if(unknown.length)throw apiError(`${path} contains unsupported fields`,400)}
function numeric(value,path,min,max){if(value===''||value===null||value===undefined)return;const parsed=Number(value);if(!Number.isFinite(parsed)||parsed<min||parsed>max)throw apiError(`${path} must be between ${min} and ${max}`,400)}
function text(value,path,max=2000){if(value===''||value===null||value===undefined)return;if(typeof value!=='string'||value.length>max)throw apiError(`${path} must be valid text`,400)}
function bool(value,path){if(value!==null&&value!==undefined&&typeof value!=='boolean')throw apiError(`${path} must be true, false, or empty`,400)}
function choice(value,allowed,path){if(value===''||value===null||value===undefined)return;if(!allowed.has(value))throw apiError(`${path} is invalid`,400)}
function selections(value,allowed,path,max=30){if(value===undefined)return;if(!Array.isArray(value)||value.length>max||value.some((item)=>typeof item!=='string'||!allowed.has(item)))throw apiError(`${path} contains invalid selections`,400)}
function textList(value,path){if(value===undefined)return;if(!Array.isArray(value)||value.length>20)throw apiError(`${path} must be a list`,400);value.forEach((item,index)=>text(item,`${path}.${index}`,500))}

function inspection(section){section=asObject(section,'inspection');knownKeys(section,new Set(['staticFindings','dynamicFindings','notes']),'inspection');selections(section.staticFindings,STATIC_FINDINGS,'inspection.staticFindings');selections(section.dynamicFindings,DYNAMIC_FINDINGS,'inspection.dynamicFindings');text(section.notes,'inspection.notes')}
function palpation(section){section=asObject(section,'palpation');knownKeys(section,new Set(['locations','notes']),'palpation');const locations=asObject(section.locations||{},'palpation.locations');knownKeys(locations,PALPATION_STRUCTURES,'palpation.locations');for(const [key,finding] of Object.entries(locations)){asObject(finding,key);knownKeys(finding,new Set(['tenderness','findings']),key);numeric(finding.tenderness,`${key}.tenderness`,0,3);selections(finding.findings,PALPATION_FINDINGS,`${key}.findings`)}text(section.notes,'palpation.notes')}
function articular(section){section=asObject(section,'articular');knownKeys(section,new Set(['movements','movementQuality','endFeel','segmentalMobility','notes']),'articular');const movements=asObject(section.movements||{},'articular.movements');knownKeys(movements,MOVEMENTS,'articular.movements');for(const [key,finding] of Object.entries(movements)){asObject(finding,key);knownKeys(finding,new Set(['arom','prom','pain','limitation']),key);numeric(finding.arom,`${key}.arom`,0,180);numeric(finding.prom,`${key}.prom`,0,180);bool(finding.pain,`${key}.pain`);bool(finding.limitation,`${key}.limitation`)}selections(section.movementQuality,MOVEMENT_QUALITY,'articular.movementQuality');choice(section.endFeel,new Set(['normal','firm','hard','empty','pain_limited']),'articular.endFeel');const mobility=asObject(section.segmentalMobility||{},'articular.segmentalMobility');knownKeys(mobility,SEGMENTS,'articular.segmentalMobility');for(const [key,value] of Object.entries(mobility))choice(value,new Set(['hypomobile','normal','hypermobile']),key);text(section.notes,'articular.notes')}
function muscular(section){section=asObject(section,'muscular');knownKeys(section,new Set(['mmt','deepNeckFlexor','muscleLength','muscleControl','notes']),'muscular');const mmt=asObject(section.mmt||{},'muscular.mmt');knownKeys(mmt,MUSCLES,'muscular.mmt');for(const [key,finding] of Object.entries(mmt)){asObject(finding,key);knownKeys(finding,new Set(['right','left','pain']),key);numeric(finding.right,`${key}.right`,0,5);numeric(finding.left,`${key}.left`,0,5);bool(finding.pain,`${key}.pain`)}choice(section.deepNeckFlexor,new Set(['normal','reduced','unable']),'muscular.deepNeckFlexor');selections(section.muscleLength,MUSCLE_LENGTH,'muscular.muscleLength');selections(section.muscleControl,MUSCLE_CONTROL,'muscular.muscleControl');text(section.notes,'muscular.notes')}
function neurological(section){section=asObject(section,'neurological');knownKeys(section,new Set(['sensory','myotomes','reflexes','reflexComparison','notes']),'neurological');const sensory=asObject(section.sensory||{},'neurological.sensory');knownKeys(sensory,DERMATOMES,'neurological.sensory');for(const [key,finding] of Object.entries(sensory)){asObject(finding,key);knownKeys(finding,new Set(['right','left']),key);for(const side of ['right','left'])choice(finding[side],new Set(['normal','hypoesthesia','paresthesia','numbness','dysesthesia']),`${key}.${side}`)}const myotomes=asObject(section.myotomes||{},'neurological.myotomes');knownKeys(myotomes,MYOTOMES,'neurological.myotomes');for(const [key,finding] of Object.entries(myotomes)){asObject(finding,key);knownKeys(finding,new Set(['right','left']),key);numeric(finding.right,`${key}.right`,0,5);numeric(finding.left,`${key}.left`,0,5)}const reflexes=asObject(section.reflexes||{},'neurological.reflexes');knownKeys(reflexes,REFLEXES,'neurological.reflexes');for(const [key,finding] of Object.entries(reflexes)){asObject(finding,key);knownKeys(finding,new Set(['right','left']),key);for(const side of ['right','left'])choice(finding[side],new Set(['0','1+','2+','3+','4+']),`${key}.${side}`)}choice(section.reflexComparison,new Set(['symmetrical','hyporeflexia','absent','hyperreflexia']),'neurological.reflexComparison');text(section.notes,'neurological.notes')}
function radicular(section){section=asObject(section,'radicular');knownKeys(section,new Set(['tests','notes']),'radicular');const tests=asObject(section.tests||{},'radicular.tests');knownKeys(tests,RADICULAR_TESTS,'radicular.tests');for(const [key,finding] of Object.entries(tests)){asObject(finding,key);knownKeys(finding,new Set(['result','familiarSymptoms','sensitizerChange','sideDifference']),key);choice(finding.result,new Set(['positive','negative','not_tested']),`${key}.result`);bool(finding.familiarSymptoms,`${key}.familiarSymptoms`);bool(finding.sensitizerChange,`${key}.sensitizerChange`);text(finding.sideDifference,`${key}.sideDifference`,500)}text(section.notes,'radicular.notes')}
function umnScreen(section){section=asObject(section,'umnScreen');knownKeys(section,new Set(['tests','myelopathySymptoms','notes']),'umnScreen');const tests=asObject(section.tests||{},'umnScreen.tests');knownKeys(tests,UMN_TESTS,'umnScreen.tests');for(const [key,value] of Object.entries(tests))choice(value,['hoffmann','babinski','clonus'].includes(key)?new Set(['positive','negative','not_tested']):new Set(['normal','abnormal','not_tested']),key);selections(section.myelopathySymptoms,MYELOPATHY_SYMPTOMS,'umnScreen.myelopathySymptoms');text(section.notes,'umnScreen.notes')}
function vascularScreen(section){section=asObject(section,'vascularScreen');knownKeys(section,new Set(['indicated','symptoms','notes']),'vascularScreen');bool(section.indicated,'vascularScreen.indicated');selections(section.symptoms,VASCULAR_SYMPTOMS,'vascularScreen.symptoms');text(section.notes,'vascularScreen.notes')}
function functional(section){section=asObject(section,'functional');knownKeys(section,new Set(['activities','tasks','notes']),'functional');const activities=asObject(section.activities||{},'functional.activities');knownKeys(activities,ACTIVITIES,'functional.activities');for(const [key,value] of Object.entries(activities))choice(value,new Set(['none','mild','moderate','severe','unable']),key);const tasks=asObject(section.tasks||{},'functional.tasks');knownKeys(tasks,FUNCTIONAL_TASKS,'functional.tasks');for(const [key,value] of Object.entries(tasks))choice(value,new Set(['normal','limited','painful','unable']),key);text(section.notes,'functional.notes')}
function motorControl(section){section=asObject(section,'motorControl');knownKeys(section,new Set(['tests','notes']),'motorControl');const tests=asObject(section.tests||{},'motorControl.tests');knownKeys(tests,MOTOR_TESTS,'motorControl.tests');for(const [key,value] of Object.entries(tests))choice(value,new Set(['normal','abnormal','positive','negative','unable','not_tested']),key);text(section.notes,'motorControl.notes')}
function specialTests(section){section=asObject(section,'specialTests');knownKeys(section,new Set(['pathways','showFull','tests','notes']),'specialTests');selections(section.pathways,PATHWAYS,'specialTests.pathways');bool(section.showFull,'specialTests.showFull');const tests=asObject(section.tests||{},'specialTests.tests');knownKeys(tests,SPECIAL_TESTS,'specialTests.tests');for(const [key,value] of Object.entries(tests))choice(value,new Set(['positive','negative','normal','abnormal','unable','not_tested']),key);text(section.notes,'specialTests.notes')}
function outcome(section){section=asObject(section,'outcomeMeasure');knownKeys(section,new Set(['ndi','psfs','notes']),'outcomeMeasure');numeric(section.ndi,'outcomeMeasure.ndi',0,50);if(section.psfs!==undefined){if(!Array.isArray(section.psfs)||section.psfs.length>3)throw apiError('PSFS must contain up to three activities',400);section.psfs.forEach((entry,index)=>{asObject(entry,`psfs.${index}`);knownKeys(entry,new Set(['activity','score']),`psfs.${index}`);text(entry.activity,`psfs.${index}.activity`,500);numeric(entry.score,`psfs.${index}.score`,0,10)})}text(section.notes,'outcomeMeasure.notes')}
function reasoning(section){section=asObject(section,'clinicalReasoning');knownKeys(section,new Set(['mainHypothesis','differentialDiagnosis','supportingFindings','againstFindings','testsNeeded','interpretation']),'clinicalReasoning');text(section.mainHypothesis,'clinicalReasoning.mainHypothesis',3000);text(section.interpretation,'clinicalReasoning.interpretation',5000);for(const key of ['differentialDiagnosis','supportingFindings','againstFindings','testsNeeded'])textList(section[key],`clinicalReasoning.${key}`)}

export function validateNeckAssessmentData(value,{completed=false}={}){
  const data=asObject(value,'assessment_data');
  if(JSON.stringify(data).length>300000)throw apiError('Assessment data is too large',413);
  knownKeys(data,new Set(SECTIONS),'assessment_data');
  if(completed){const missing=SECTIONS.filter((key)=>!data[key]);if(missing.length)throw apiError('All assessment sections must be present before completion',400)}
  const validators=[inspection,palpation,articular,muscular,neurological,radicular,umnScreen,vascularScreen,functional,motorControl,specialTests,outcome,reasoning];
  SECTIONS.forEach((key,index)=>{if(data[key]!==undefined)validators[index](data[key])});
  return data;
}
