import express from 'express';
import { requireAuth } from '../middleware/requireAuth.js';
import { requireRole } from '../middleware/requireRole.js';
import * as clinician from '../controllers/physiotherapistController.js';
import * as clinicalAssessment from '../controllers/clinicalAssessmentController.js';

const router = express.Router();
router.use(requireAuth, requireRole('physiotherapist'));
router.route('/me').get(clinician.me).patch(clinician.me);
router.route('/availability').get(clinician.availability).post(clinician.availability);
router.route('/availability/:id').patch(clinician.updateAvailability).delete(clinician.deleteAvailability);
router.route('/time-off').get(clinician.timeOff).post(clinician.timeOff);
router.delete('/time-off/:id', clinician.deleteTimeOff);
router.get('/appointments', clinician.appointments);
router.get('/appointments/:id/evaluation-context', clinician.evaluationContext);
router.post('/appointments/:id/complete', clinician.completeAppointment);
router.patch('/appointments/:id/status', clinician.updateAppointmentStatus);
router.get('/patients', clinician.patients);
router.get('/patients/:patientId/clinical-profile', clinicalAssessment.clinicalProfile);
router.post('/patients/:patientId/assessments', clinicalAssessment.createAssessment);
router.get('/patients/:patientId/assessments/:assessmentId', clinicalAssessment.getAssessment);
router.patch('/patients/:patientId/assessments/:assessmentId', clinicalAssessment.updateAssessment);
router.post('/patients/:patientId/assessments/:assessmentId/reassess', clinicalAssessment.reassess);
router.get('/patients/:id', clinician.patients);
export default router;
