import { BooleanChoice, ChoiceButtons, DualLabel, FindingCard, MultiCheck, NotesField, NumberField } from '../../components/AssessmentControls.jsx'
import { cervicalTests, dermatomes, functionalActivities, functionalTests, muscleLength, muscles, myotomes, peripheralNerves, reflexes, scapularControl, sports } from '../shoulderConfig.js'

const sensoryOptions = [{key:'normal',label:'Normal',labelAr:'طبيعي'},{key:'hypoesthesia',label:'Hypoesthesia',labelAr:'نقص الحس'},{key:'paresthesia',label:'Paresthesia',labelAr:'تنميل'},{key:'numbness',label:'Numbness',labelAr:'خدر'},{key:'dysesthesia',label:'Dysesthesia',labelAr:'عسر الحس'}]
const reflexOptions = ['0','1+','2+','3+','4+'].map((key)=>({key,label:key,labelAr:key}))
const difficultyOptions = [{key:'none',label:'None',labelAr:'لا يوجد'},{key:'mild',label:'Mild',labelAr:'خفيف'},{key:'moderate',label:'Moderate',labelAr:'متوسط'},{key:'severe',label:'Severe',labelAr:'شديد'},{key:'unable',label:'Unable',labelAr:'غير قادر'}]

export function MuscularSection({ value, onChange }) {
  function finding(key) { return value.mmt[key]||{right:'',left:'',pain:null} }
  function update(key,field,nextValue){onChange({...value,mmt:{...value.mmt,[key]:{...finding(key),[field]:nextValue}}})}
  return <div className="assessment-section__body"><section className="clinical-subsection"><DualLabel as="h3" label="Manual Muscle Testing — MMT 0–5" labelAr="اختبار القوة العضلية اليدوي — من 0 إلى 5"/><div className="mmt-grid">{muscles.map((item)=>{const current=finding(item.key);return <article className="mmt-card" key={item.key}><DualLabel as="h4" label={item.label} labelAr={item.labelAr}/><div><NumberField label="Right" labelAr="يمين" min="0" max="5" suffix="/5" value={current.right} onChange={(next)=>update(item.key,'right',next)}/><NumberField label="Left" labelAr="يسار" min="0" max="5" suffix="/5" value={current.left} onChange={(next)=>update(item.key,'left',next)}/></div><BooleanChoice label="Pain" labelAr="ألم" value={current.pain} onChange={(next)=>update(item.key,'pain',next)}/></article>})}</div></section><MultiCheck label="Muscle Length" labelAr="طول العضلات" options={muscleLength} value={value.muscleLength} onChange={(next)=>onChange({...value,muscleLength:next})}/><MultiCheck label="Scapular Control" labelAr="التحكم بلوح الكتف" options={scapularControl} value={value.scapularControl} onChange={(next)=>onChange({...value,scapularControl:next})}/><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

function BilateralScores({ items, values, onChange, options }) {
  return <div className="bilateral-grid">{items.map((item)=>{const current=values[item.key]||{};return <article key={item.key}><DualLabel as="h4" label={item.label} labelAr={item.labelAr}/><div>{options?<><ChoiceButtons label="Right" labelAr="يمين" options={options} value={current.right||''} onChange={(next)=>onChange({...values,[item.key]:{...current,right:next}})}/><ChoiceButtons label="Left" labelAr="يسار" options={options} value={current.left||''} onChange={(next)=>onChange({...values,[item.key]:{...current,left:next}})}/></>:<><NumberField label="Right" labelAr="يمين" min="0" max="5" suffix="/5" value={current.right??''} onChange={(next)=>onChange({...values,[item.key]:{...current,right:next}})}/><NumberField label="Left" labelAr="يسار" min="0" max="5" suffix="/5" value={current.left??''} onChange={(next)=>onChange({...values,[item.key]:{...current,left:next}})}/></>}</div></article>})}</div>
}

function FindingInputs({ items, values, onChange }) {
  return <div className="clinical-field-grid">{items.map((item)=><label className="clinical-text-field" key={item.key}><DualLabel label={item.label} labelAr={item.labelAr}/><input value={values[item.key]||''} placeholder="Result / finding" onChange={(event)=>onChange({...values,[item.key]:event.target.value})}/></label>)}</div>
}

export function NeurologicalSection({ value, onChange }) {
  return <div className="assessment-section__body"><section className="clinical-subsection"><DualLabel as="h3" label="Sensory / Dermatomes" labelAr="الإحساس / القطاعات الجلدية"/><BilateralScores items={dermatomes} values={value.sensory} options={sensoryOptions} onChange={(sensory)=>onChange({...value,sensory})}/></section><section className="clinical-subsection"><DualLabel as="h3" label="Myotomes" labelAr="القطاعات العضلية"/><BilateralScores items={myotomes} values={value.myotomes} onChange={(myotomesValue)=>onChange({...value,myotomes:myotomesValue})}/></section><section className="clinical-subsection"><DualLabel as="h3" label="Reflexes" labelAr="المنعكسات"/><BilateralScores items={reflexes} values={value.reflexes} options={reflexOptions} onChange={(reflexValues)=>onChange({...value,reflexes:reflexValues})}/></section><section className="clinical-subsection"><DualLabel as="h3" label="Cervical Screen" labelAr="فحص الرقبة"/><FindingInputs items={cervicalTests} values={value.cervicalScreen} onChange={(cervicalScreen)=>onChange({...value,cervicalScreen})}/></section><section className="clinical-subsection"><DualLabel as="h3" label="Peripheral Nerves" labelAr="الأعصاب الطرفية"/><FindingInputs items={peripheralNerves} values={value.peripheralNerves} onChange={(peripheralNervesValue)=>onChange({...value,peripheralNerves:peripheralNervesValue})}/></section><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function FunctionalSection({ value, onChange }) {
  function activity(key){return value.activities[key]||{difficulty:'',symptoms:''}}
  function updateActivity(key,field,nextValue){onChange({...value,activities:{...value.activities,[key]:{...activity(key),[field]:nextValue}}})}
  function toggleTest(key,active){const tests={...value.tests};if(active)tests[key]={performed:true,result:'',notes:''};else delete tests[key];onChange({...value,tests})}
  function updateTest(key,field,nextValue){onChange({...value,tests:{...value.tests,[key]:{...value.tests[key],[field]:nextValue}}})}
  return <div className="assessment-section__body"><section className="clinical-subsection"><DualLabel as="h3" label="Basic Function" labelAr="الوظائف الأساسية"/><div className="functional-activity-grid">{functionalActivities.map((item)=>{const current=activity(item.key);return <article key={item.key}><DualLabel as="h4" label={item.label} labelAr={item.labelAr}/><ChoiceButtons label="Difficulty" labelAr="درجة الصعوبة" options={difficultyOptions} value={current.difficulty} onChange={(next)=>updateActivity(item.key,'difficulty',next)}/><label className="clinical-text-field"><DualLabel label="Symptoms" labelAr="الأعراض"/><input value={current.symptoms} onChange={(event)=>updateActivity(item.key,'symptoms',event.target.value)}/></label></article>})}</div></section><label className="clinical-range"><DualLabel label="Pain During Function" labelAr="الألم أثناء النشاط"/><input type="range" min="0" max="10" step="1" value={value.painDuringFunction===''?0:value.painDuringFunction} onChange={(event)=>onChange({...value,painDuringFunction:Number(event.target.value)})}/><output>{value.painDuringFunction===''?'—':value.painDuringFunction} / 10</output></label><MultiCheck label="Sport" labelAr="النشاط الرياضي" options={sports} value={value.sports} onChange={(next)=>onChange({...value,sports:next})}/><section className="clinical-subsection"><DualLabel as="h3" label="Functional Tests Performed" labelAr="الاختبارات الوظيفية المنفذة"/><div className="clinical-finding-grid">{functionalTests.map((item)=>{const current=value.tests[item.key];return <FindingCard item={item} key={item.key} active={Boolean(current)} onToggle={(active)=>toggleTest(item.key,active)}>{current&&<div className="clinical-field-grid"><label className="clinical-text-field"><DualLabel label="Result" labelAr="النتيجة"/><input value={current.result} onChange={(event)=>updateTest(item.key,'result',event.target.value)}/></label><NotesField label="Test Notes" labelAr="ملاحظات الاختبار" rows={2} value={current.notes} onChange={(notes)=>updateTest(item.key,'notes',notes)}/></div>}</FindingCard>})}</div></section><NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}
