import { ChoiceButtons, DualLabel, MultiCheck, NotesField, NumberField, TextList } from '../../components/AssessmentControls.jsx'
import { hypotheses, outcomeMeasures, targetedTests } from '../shoulderConfig.js'

export function SpecialTestsSection({ value, onChange }) {
  const visibleTests = [...new Map(value.hypotheses.flatMap((key)=>targetedTests[key]||[]).map((test)=>[test.key,test])).values()]
  function finding(key){return value.tests[key]||{result:'not_performed',pain:'',notes:''}}
  function update(key,field,nextValue){onChange({...value,tests:{...value.tests,[key]:{...finding(key),[field]:nextValue}}})}
  return <div className="assessment-section__body"><div className="clinical-guidance clinical-guidance--important"><strong>Clinical decision support—not an automatic diagnosis.</strong><span dir="rtl" lang="ar">أداة لتنظيم القرار السريري وليست تشخيصاً آلياً.</span></div><MultiCheck label="What is your current clinical hypothesis?" labelAr="ما هي الفرضية السريرية الحالية؟" options={hypotheses} value={value.hypotheses} onChange={(next)=>onChange({...value,hypotheses:next})}/>{visibleTests.length?<section className="clinical-subsection"><DualLabel as="h3" label="Targeted tests" labelAr="الاختبارات الموجّهة"/><p className="clinical-guidance">Document only tests you choose to perform. A positive result is not a confirmed diagnosis.</p><div className="special-test-grid">{visibleTests.map((test)=>{const current=finding(test.key);return <article key={test.key}><DualLabel as="h4" label={test.label} labelAr={test.labelAr}/><ChoiceButtons label="Result" labelAr="النتيجة" value={current.result} allowClear={false} onChange={(next)=>update(test.key,'result',next)} options={[{key:'positive',label:'Positive',labelAr:'إيجابي'},{key:'negative',label:'Negative',labelAr:'سلبي'},{key:'not_performed',label:'Not Performed',labelAr:'لم يُجرَ'}]}/><label className="clinical-text-field"><DualLabel label="Pain (optional)" labelAr="الألم (اختياري)"/><input value={current.pain} onChange={(event)=>update(test.key,'pain',event.target.value)}/></label><NotesField label="Notes" labelAr="ملاحظات" rows={2} value={current.notes} onChange={(notes)=>update(test.key,'notes',notes)}/></article>})}</div></section>:<div className="clinical-empty-inline">Select one or more hypotheses to reveal relevant tests. / اختر فرضية أو أكثر لإظهار الاختبارات المناسبة.</div>}<NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}

export function ClinicalReasoningSection({ value, onChange }) {
  return <div className="assessment-section__body"><div className="clinical-guidance clinical-guidance--important"><strong>The clinician remains responsible for interpretation.</strong><span dir="rtl" lang="ar">يبقى الأخصائي مسؤولاً عن التفسير السريري.</span></div><NotesField label="Primary Hypothesis" labelAr="الفرضية الأساسية" value={value.primaryHypothesis} onChange={(primaryHypothesis)=>onChange({...value,primaryHypothesis})}/><TextList label="Differential Diagnosis" labelAr="التشخيص التفريقي" values={value.differentialDiagnosis} onChange={(differentialDiagnosis)=>onChange({...value,differentialDiagnosis})}/><TextList label="Findings Supporting Hypothesis" labelAr="النتائج الداعمة للفرضية" values={value.supportingFindings} onChange={(supportingFindings)=>onChange({...value,supportingFindings})}/><TextList label="Findings Against Hypothesis" labelAr="النتائج غير الداعمة للفرضية" values={value.againstFindings} onChange={(againstFindings)=>onChange({...value,againstFindings})}/><TextList label="Tests Needed for Confirmation" labelAr="الاختبارات اللازمة للتأكيد" values={value.confirmationTests} onChange={(confirmationTests)=>onChange({...value,confirmationTests})}/><NotesField label="Clinical Interpretation" labelAr="التفسير السريري" rows={6} value={value.interpretation} onChange={(interpretation)=>onChange({...value,interpretation})}/></div>
}

export function OutcomeMeasureSection({ value, onChange }) {
  const selected = outcomeMeasures.find((item)=>item.key===value.measure)
  function score(group,field,nextValue){onChange({...value,[group]:{...value[group],[field]:nextValue}})}
  return <div className="assessment-section__body"><div className="clinical-guidance">Record clinician-entered scores only. No scoring formula or interpretation is generated. / سجّل الدرجات المدخلة من الأخصائي فقط دون احتساب أو تفسير آلي.</div><section className="outcome-options"><DualLabel as="h3" label="Choose an outcome measure" labelAr="اختر مقياس النتيجة"/>{outcomeMeasures.map((measure)=><label className={value.measure===measure.key?'is-selected':''} key={measure.key}><input type="radio" checked={value.measure===measure.key} onChange={()=>onChange({...value,measure:measure.key})}/><DualLabel label={measure.label} labelAr={measure.labelAr}/><small>{measure.description}</small></label>)}</section>{selected&&<section className="outcome-scores"><DualLabel as="h3" label={`${selected.label} scores`} labelAr="درجات المقياس"/><div><article><DualLabel as="h4" label="Baseline Score" labelAr="درجة خط الأساس"/><NumberField label="Score" labelAr="الدرجة" min="0" max="100000" value={value.baseline.score??''} onChange={(next)=>score('baseline','score',next)}/><NumberField label="Denominator" labelAr="المقام" min="1" max="100000" value={value.baseline.denominator??''} onChange={(next)=>score('baseline','denominator',next)}/></article><article><DualLabel as="h4" label="Reassessment Score" labelAr="درجة إعادة التقييم"/><NumberField label="Score" labelAr="الدرجة" min="0" max="100000" value={value.reassessment.score??''} onChange={(next)=>score('reassessment','score',next)}/><NumberField label="Denominator" labelAr="المقام" min="1" max="100000" value={value.reassessment.denominator??''} onChange={(next)=>score('reassessment','denominator',next)}/></article></div></section>}<NotesField value={value.notes} onChange={(notes)=>onChange({...value,notes})}/></div>
}
