const item=(key,label,labelAr)=>({key,label,labelAr})
export const elbowSteps=[
  item('inspection','Inspection','الفحص البصري'),item('palpation','Palpation','الجس'),item('articular','Articular Assessment','التقييم المفصلي'),
  item('strengthMobility','Alignment, Mobility & Muscular','المحاذاة والحركة والتقييم العضلي'),item('neurological','Neurological Screen','الفحص العصبي'),
  item('specialTests','Targeted Special Tests','الاختبارات الخاصة الموجّهة'),item('functional','Functional Assessment','التقييم الوظيفي'),
  item('outcomeMeasure','Outcome Measures','مقاييس النتائج'),item('clinicalReasoning','Clinical Reasoning','الاستدلال السريري'),
]
export const staticFindings=[item('posture','Posture','الوضعية'),item('carrying_angle','Carrying angle','زاوية الحمل'),item('valgus','Valgus','أروح'),item('varus','Varus','فحج'),item('deformity','Deformity','تشوه'),item('swelling','Swelling / oedema','تورم / وذمة'),item('ecchymosis','Ecchymosis','كدمات'),item('redness','Redness','احمرار'),item('scar','Scar','ندبة'),item('muscle_atrophy','Muscle atrophy','ضمور عضلي'),item('asymmetry','Asymmetry','عدم تماثل'),item('protective_position','Protective position','وضعية وقائية')]
export const elbowMovements=[item('flexion','Flexion','الثني'),item('extension','Extension','المد'),item('pronation','Pronation','الكب'),item('supination','Supination','الاستلقاء')]
export const dynamicFindings=[item('limited_rom','Limited ROM','محدودية الحركة'),item('painful_movement','Painful movement','حركة مؤلمة'),item('compensation','Compensation','تعويض'),item('instability','Instability','عدم ثبات'),item('crepitus','Crepitus','فرقعة'),item('locking','Locking','انقفال'),item('catching','Catching','تعليق')]
export const palpationGroups=[
  {label:'Bony Structures',labelAr:'البنى العظمية',items:[item('medial_epicondyle','Medial epicondyle','اللقيمة الإنسية'),item('lateral_epicondyle','Lateral epicondyle','اللقيمة الوحشية'),item('olecranon','Olecranon','الزج'),item('radial_head','Radial head','رأس الكعبرة'),item('capitulum','Capitulum','الرؤيس'),item('trochlea','Trochlea','البكرة'),item('coronoid_process','Coronoid process','الناتئ الإكليلي'),item('ulnar_shaft','Ulnar shaft','جسم الزند'),item('radial_shaft','Radial shaft','جسم الكعبرة')]},
  {label:'Joints',labelAr:'المفاصل',items:[item('humeroulnar_joint','Humeroulnar joint','المفصل العضدي الزندي'),item('humeroradial_joint','Humeroradial joint','المفصل العضدي الكعبري'),item('proximal_radioulnar_joint','Proximal radioulnar joint','المفصل الكعبري الزندي القريب')]},
  {label:'Soft Tissue',labelAr:'الأنسجة الرخوة',items:[item('common_extensor_tendon','Common extensor tendon','وتر الباسطات المشترك'),item('common_flexor_tendon','Common flexor tendon','وتر القابضات المشترك'),item('biceps_tendon','Biceps tendon','وتر ذات الرأسين'),item('triceps_tendon','Triceps tendon','وتر ثلاثية الرؤوس'),item('brachialis','Brachialis','العضدية'),item('pronator_teres','Pronator teres','الكابة المدورة'),item('supinator','Supinator','العضلة الاستلقائية'),item('anconeus','Anconeus','المرفقية')]},
]
export const palpationFindings=[item('local_tenderness','Local tenderness','إيلام موضعي'),item('swelling','Swelling','تورم'),item('increased_temperature','Increased temperature','ارتفاع الحرارة'),item('muscle_spasm','Muscle spasm','تشنج عضلي'),item('trigger_point','Trigger point','نقطة زناد'),item('tendon_tenderness','Tendon tenderness','إيلام الوتر')]
export const movementQuality=[item('normal','Normal','طبيعي'),item('stiffness','Stiffness','تيبس'),item('pain','Pain','ألم'),item('catching','Catching','تعليق'),item('crepitus','Crepitus','فرقعة'),item('locking','Locking','انقفال')]
export const accessoryGroups=[
  {label:'Humeroulnar',labelAr:'العضدي الزندي',items:[item('humeroulnar_medial','Medial glide','انزلاق إنسي'),item('humeroulnar_lateral','Lateral glide','انزلاق وحشي'),item('humeroulnar_anterior','Anterior glide','انزلاق أمامي'),item('humeroulnar_posterior','Posterior glide','انزلاق خلفي')]},
  {label:'Humeroradial',labelAr:'العضدي الكعبري',items:[item('humeroradial_anterior','Anterior glide','انزلاق أمامي'),item('humeroradial_posterior','Posterior glide','انزلاق خلفي')]},
  {label:'Proximal Radioulnar',labelAr:'الكعبري الزندي القريب',items:[item('radial_head_anterior','Radial head anterior glide','انزلاق رأس الكعبرة الأمامي'),item('radial_head_posterior','Radial head posterior glide','انزلاق رأس الكعبرة الخلفي')]},
]
export const muscles=[item('biceps','Biceps','ذات الرأسين'),item('brachialis','Brachialis','العضدية'),item('brachioradialis','Brachioradialis','العضدية الكعبرية'),item('triceps','Triceps','ثلاثية الرؤوس'),item('wrist_extensors','Wrist extensors','باسطات المعصم'),item('wrist_flexors','Wrist flexors','قابضات المعصم'),item('pronators','Pronators','الكابات'),item('supinators','Supinators','الاستلقائيات'),item('grip','Grip','القبضة')]
export const muscleLength=[item('wrist_flexor_tightness','Wrist flexor tightness','قصر قابضات المعصم'),item('wrist_extensor_tightness','Wrist extensor tightness','قصر باسطات المعصم'),item('pronator_tightness','Pronator tightness','قصر الكابات'),item('supinator_tightness','Supinator tightness','قصر الاستلقائيات'),item('biceps_tightness','Biceps tightness','قصر ذات الرأسين'),item('triceps_tightness','Triceps tightness','قصر ثلاثية الرؤوس')]
export const dermatomes=[item('c5','C5 — Lateral arm','C5 — الجانب الوحشي للذراع'),item('c6','C6 — Thumb','C6 — الإبهام'),item('c7','C7 — Middle finger','C7 — الإصبع الأوسط'),item('c8','C8 — Little finger','C8 — الخنصر'),item('t1','T1 — Medial forearm','T1 — الجانب الإنسي للساعد')]
export const nerves=[
  {key:'radial',label:'Radial Nerve',labelAr:'العصب الكعبري',checks:[item('wrist_extension','Wrist extension','مد المعصم'),item('finger_extension','Finger extension','مد الأصابع'),item('sensory_dorsal_hand','Sensory dorsal hand','إحساس ظهر اليد')]},
  {key:'median',label:'Median Nerve',labelAr:'العصب المتوسط',checks:[item('wrist_finger_flexion','Wrist/finger flexion','ثني المعصم والأصابع'),item('thumb_opposition','Thumb opposition','مقابلة الإبهام'),item('sensory_radial_palm','Sensory radial palm','إحساس راحة اليد الكعبرية')]},
  {key:'ulnar',label:'Ulnar Nerve',labelAr:'العصب الزندي',checks:[item('finger_abduction','Finger abduction/adduction','تبعيد وتقريب الأصابع'),item('grip','Grip','القبضة'),item('sensory_little_finger','Sensory little finger','إحساس الخنصر')]},
]
export const reflexes=[item('biceps_c5_6','Biceps C5–C6','ذات الرأسين C5–C6'),item('brachioradialis_c6','Brachioradialis C6','العضدية الكعبرية C6'),item('triceps_c7','Triceps C7','ثلاثية الرؤوس C7')]
export const neurodynamic=[item('ultt1','ULTT1 — Median nerve','ULTT1 — العصب المتوسط'),item('ultt2a','ULTT2a — Median nerve','ULTT2a — العصب المتوسط'),item('ultt2b','ULTT2b — Radial nerve','ULTT2b — العصب الكعبري'),item('ultt3','ULTT3 — Ulnar nerve','ULTT3 — العصب الزندي')]
export const pathways=[item('lateral','Lateral elbow pain','ألم المرفق الوحشي'),item('medial','Medial elbow pain','ألم المرفق الإنسي'),item('anterior','Anterior elbow symptoms','أعراض المرفق الأمامية'),item('posterior','Posterior elbow symptoms','أعراض المرفق الخلفية'),item('instability','Instability suspected','اشتباه عدم الثبات'),item('posterolateral_instability','Posterolateral instability','عدم الثبات الدوراني الخلفي الوحشي'),item('ulnar_nerve','Ulnar nerve symptoms','أعراض العصب الزندي'),item('radioulnar','Radioulnar symptoms','أعراض كعبرية زندية'),item('neurological','Neurological symptoms','أعراض عصبية')]
export const specialTestGroups={
  lateral:{label:'Lateral Epicondylalgia',labelAr:'ألم اللقيمة الوحشية',tests:[item('resisted_wrist_extension','Resisted Wrist Extension','مد المعصم ضد المقاومة'),item('cozens',"Cozen's Test",'اختبار كوزن'),item('mills',"Mill's Test",'اختبار ميل'),item('maudsleys',"Maudsley's Test",'اختبار مودسلي')]},
  medial:{label:'Medial Epicondylalgia',labelAr:'ألم اللقيمة الإنسية',tests:[item('resisted_wrist_flexion','Resisted Wrist Flexion','ثني المعصم ضد المقاومة'),item('resisted_pronation_medial','Resisted Pronation','الكب ضد المقاومة'),item('golfers_elbow',"Golfer's Elbow Test",'اختبار مرفق لاعب الغولف')]},
  anterior:{label:'Distal Biceps Tendinopathy / Tear',labelAr:'اعتلال / تمزق وتر ذات الرأسين البعيد',tests:[item('resisted_supination_biceps','Resisted Supination','الاستلقاء ضد المقاومة'),item('resisted_elbow_flexion','Resisted Elbow Flexion','ثني المرفق ضد المقاومة'),item('hook_test','Hook Test','اختبار الخطاف')]},
  posterior:{label:'Triceps Tendinopathy / Injury',labelAr:'اعتلال / إصابة ثلاثية الرؤوس',tests:[item('resisted_elbow_extension','Resisted Elbow Extension','مد المرفق ضد المقاومة'),item('triceps_palpation','Triceps Palpation','جس وتر ثلاثية الرؤوس')]},
  instability:{label:'Elbow Instability',labelAr:'عدم ثبات المرفق',tests:[item('valgus_stress','Valgus Stress Test','اختبار الإجهاد الأروح'),item('varus_stress','Varus Stress Test','اختبار الإجهاد الفحج'),item('moving_valgus','Moving Valgus Stress Test','اختبار الإجهاد الأروح المتحرك')]},
  posterolateral_instability:{label:'Posterolateral Rotatory Instability',labelAr:'عدم الثبات الدوراني الخلفي الوحشي',tests:[item('lateral_pivot_shift','Lateral Pivot-Shift Test','اختبار التحول المحوري الوحشي'),item('chair_push_up_instability','Chair Push-up Test','اختبار الضغط على الكرسي')]},
  ulnar_nerve:{label:'Ulnar Nerve',labelAr:'العصب الزندي',tests:[item('tinels_cubital',"Tinel's Sign at Cubital Tunnel",'علامة تينل في النفق المرفقي'),item('elbow_flexion_test','Elbow Flexion Test','اختبار ثني المرفق'),item('ulnar_neurodynamic','Ulnar Neurodynamic Test','اختبار الديناميكا العصبية الزندية')]},
  radioulnar:{label:'Distal / Proximal Radioulnar',labelAr:'الكعبري الزندي البعيد / القريب',tests:[item('radial_head_mobility','Radial head mobility','حركة رأس الكعبرة'),item('proximal_radioulnar_assessment','Proximal radioulnar assessment','تقييم المفصل الكعبري الزندي القريب'),item('resisted_supination_radioulnar','Resisted supination','الاستلقاء ضد المقاومة'),item('resisted_pronation_radioulnar','Resisted pronation','الكب ضد المقاومة')]},
}
export const activities=[item('eating','Eating','الأكل'),item('drinking','Drinking','الشرب'),item('dressing','Dressing','ارتداء الملابس'),item('washing_hair','Washing hair','غسل الشعر'),item('brushing_teeth','Brushing teeth','تنظيف الأسنان'),item('carrying_objects','Carrying objects','حمل الأشياء'),item('opening_door','Opening door','فتح الباب'),item('opening_jar','Opening jar','فتح المرطبان'),item('writing','Writing','الكتابة'),item('computer_mouse','Computer / mouse use','استخدام الكمبيوتر / الفأرة')]
export const sports=[item('tennis','Tennis','التنس'),item('golf','Golf','الغولف'),item('boxing','Boxing','الملاكمة'),item('weightlifting','Weightlifting','رفع الأثقال'),item('climbing','Climbing','التسلق'),item('throwing','Throwing','الرمي'),item('racquet_sports','Racquet sports','رياضات المضرب'),item('manual_work','Manual work','العمل اليدوي')]
